const {serve,root}=require('./server.cjs');
const {chromium}=require('playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
async function run(){
 const server=await serve(),browser=await chromium.launch({executablePath:process.env.UI_REFERENCE_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const errors=[],results=[],requests=[];let page;
 try{
  page=await browser.newPage({viewport:{width:720,height:700}});page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.stack));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
  const fresh=async()=>{await page.goto(server.url+'/client/reference/index.html');await page.waitForFunction(()=>window.ReferenceState);};
  const navigate=async(route,variant)=>{await page.locator('[data-route='+route+']').click();if(await page.locator('[data-answer=discard]').count())await page.locator('[data-answer=discard]').click();if(variant){await page.locator('[data-variant='+variant+']').click();if(await page.locator('[data-answer=discard]').count())await page.locator('[data-answer=discard]').click();}await page.waitForTimeout(30);assert.equal(await page.evaluate(()=>ReferenceState().route),route);};
  const state=()=>page.evaluate(()=>ReferenceState());
  const ok=name=>{results.push({name,result:'PASS'});console.log('PASS '+name);};
  await fresh();results.push({ua:await page.evaluate(()=>navigator.userAgent)});
  await page.locator('[data-reg-tab=componentKind][data-value=iconGrid]').click();assert.ok(await page.locator('[data-reg-value=columns]').first().isVisible());assert.equal(await page.locator('[data-reg-value=paddingX]').count(),0);
  await page.locator('[data-reg-context]').selectOption('noComp',{force:true});assert.ok(await page.locator('[data-reg-action=createIconGrid]').isDisabled());await page.locator('[data-reg-context]').selectOption('text',{force:true});await page.locator('[data-action-error]').check();await page.locator('[data-reg-action=createIconGrid]').click();await page.locator('select[data-theme]').evaluate(el=>el._coreSelectComponent.trigger.focus());await page.waitForTimeout(450);assert.equal(await page.locator('select[data-theme]').evaluate(el=>el._coreSelectComponent.trigger===document.activeElement),true);assert.equal((await state()).values.lastResult.ok,false);assert.match(await page.locator('.reg-feedback').innerText(),/supported 2D layers/);ok('Kit actual conditions, context-disabled action and failed result');
  await navigate('registry','controls');const number=page.locator('[data-reg-value=numberValue]'),before=(await state()).values.values.numberValue;
  await number.fill('999');assert.equal((await state()).values.values.numberValue,before);assert.equal(await number.getAttribute('aria-invalid'),'true');await number.press('Enter');assert.equal(await number.inputValue(),'100');assert.equal((await state()).values.values.numberValue,100);
  await page.locator('[data-route=settings]').click();assert.equal((await state()).route,'registry');await page.locator('[data-answer=stay]').click();assert.equal((await state()).route,'registry');await page.locator('[data-route=settings]').click();await page.keyboard.press('Escape');assert.equal(await page.locator('.ref-modal').count(),0);assert.equal((await state()).route,'registry');ok('Number draft/commit and leave negotiation before route disposal');
  await page.locator('[data-reg-search]').fill('defaultCurve');const x=page.locator('[data-reg-curve-value=defaultCurve][data-axis=x1]');await x.fill('9');assert.equal((await state()).values.values.defaultCurve.x1,.25);await x.press('Enter');assert.equal(await x.inputValue(),'1');
  await page.setViewportSize({width:420,height:640});await page.waitForTimeout(80);const size=await page.locator('.reg-curve-graph').evaluate(el=>({width:el.clientWidth,box:+el.getAttribute('viewBox').split(' ')[2]}));assert.ok(Math.abs(size.width-size.box)<2);ok('Curve draft/commit and filtered graph resize');
  await page.locator('[data-save]').click();const curveBefore=(await state()).values.values.defaultCurve;const handle=page.locator('[data-reg-handle]').first();await handle.scrollIntoViewIfNeeded();let box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x-30,box.y+20,{steps:5});assert.equal((await state()).gesture,true);await handle.dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();await page.waitForTimeout(60);assert.equal((await state()).gesture,false);assert.deepEqual((await state()).values.values.defaultCurve,curveBefore);ok('Registry pointercancel restores draft and drops pending frame');
  await navigate('settings');await page.locator('[data-reg-search]').fill('base.accent');const accent=page.locator('[data-reg-value="base.accent"]');await accent.fill('#FF0000');await accent.blur();assert.ok((await state()).dirty);await page.locator('[data-failure]').check();await page.locator('[data-save]').click();assert.match(await page.locator('[data-reference-status]').innerText(),/failed/i);assert.equal(await accent.inputValue(),'#FF0000');await page.locator('[data-route=palette]').click();await page.locator('[data-answer=save]').click();assert.equal((await state()).route,'settings');await page.locator('[data-failure]').uncheck();await page.locator('[data-save]').click();assert.match(await page.locator('[data-reference-status]').innerText(),/persisted: false/);ok('Settings preview, save failure, retained draft, retry checkpoint');
  await fresh();await navigate('vela');assert.equal(await page.locator('#ref-draft').isDisabled(),false);await page.locator('#ref-draft').fill('中文草稿');await page.locator('#ref-draft').press('Enter');assert.equal(await page.locator('#ref-draft').inputValue(),'中文草稿\n');await page.locator('#ref-draft').dispatchEvent('compositionstart');await page.locator('#ref-draft').press('Control+Enter');assert.equal(await page.locator('#ref-draft').inputValue(),'中文草稿\n');await page.locator('#ref-draft').dispatchEvent('compositionend');await page.locator('#ref-draft').press('Control+Enter');assert.equal(await page.locator('#ref-draft').inputValue(),'');await page.locator('#ref-draft').fill('Meta fixture');await page.locator('#ref-draft').press('Meta+Enter');assert.equal(await page.locator('#ref-draft').inputValue(),'');assert.match(await page.locator('.ref-transcript').innerText(),/中文草稿/);ok('Provider-independent draft, newline, Ctrl+Enter and IME guard');
  for(const name of ['review','executing','partial','rejected','cancelled','failed','completed']){await page.locator('[data-vela-state]').selectOption(name,{force:true});assert.equal(await page.locator('.ref-projection header .ref-state').getAttribute('data-phase'),name);if(name==='partial'){await page.locator('.ref-review-identity').evaluateAll(list=>list.forEach(el=>el.open=true));const text=await page.locator('.ref-projection').innerText();assert.match(text,/verified-match/);assert.match(text,/committed-target/);assert.match(text,/Completed: 1/);assert.match(text,/ae-project-1-item-1-layer-2/);}}
  await page.locator('[data-vela-state]').selectOption('review',{force:true});await page.locator('.ref-review-identity summary').click();assert.match(await page.locator('.proposal').innerText(),/20%/);const prior=await page.locator('.ref-projection').innerText();await page.locator('[data-isolated-command=approve]').click();assert.equal(await page.locator('.ref-projection').innerText(),prior);ok('Seven port-backed states, current-step review, original target and command isolation');
  for(let i=0;i<8;i++)await page.locator('[data-vela-long]').evaluate(el=>el.click());await page.locator('.ref-transcript').evaluate(el=>el.scrollTop=160);await page.locator('#ref-draft').focus();const anchor=await page.locator('.ref-transcript').evaluate(el=>el.scrollTop);await page.locator('[data-vela-long]').evaluate(el=>el.click());assert.equal(await page.locator('.ref-transcript').evaluate(el=>el.scrollTop),anchor);assert.equal(await page.locator('#ref-draft').evaluate(el=>el===document.activeElement),true);await page.locator('[data-route=palette]').click();assert.ok(await page.locator('[data-answer=stay]').isVisible());assert.equal((await state()).route,'vela');await page.locator('[data-answer=discard]').click();ok('Nonempty conversation confirmation and append preserves reading/focus');
  await page.setViewportSize({width:720,height:700});await page.locator('[data-pal-action=open-color]').scrollIntoViewIfNeeded();const paletteBefore=(await state()).palette;await page.locator('[data-pal-action=open-color]').click();await page.locator('[data-cp-field=hex]').fill('#FF0000');await page.locator('[data-cp-field=hex]').press('Enter');assert.deepEqual((await state()).palette,paletteBefore);await page.keyboard.press('Escape');await page.waitForTimeout(300);assert.deepEqual((await state()).palette,paletteBefore);assert.equal(await page.locator('[data-pal-action=open-color]').evaluate(el=>el===document.activeElement),true);ok('Popover preview/cancel leaves asset unchanged and restores focus');
  await page.locator('[data-pal-action=open-color]').click();await page.waitForTimeout(40);await page.locator('[data-pal-action=open-color]').evaluate(el=>el.click());await page.waitForTimeout(20);await page.locator('[data-pal-action=open-color]').evaluate(el=>el.click());assert.equal(await page.locator('.color-picker-layer').count(),1);await page.locator('[data-cp-field=hex]').fill('#25AA55');await page.locator('[data-cp-action=apply]').click();await page.waitForTimeout(300);assert.notDeepEqual((await state()).palette,paletteBefore);await page.locator('[data-save]').click();ok('Popover reverse/interrupt and explicit apply/checkpoint');
  const gradient=(await state()).palette.palettes[0].slots.find(s=>s.paint.kind==='gradient');await page.locator('[data-pal-action=select-slot][data-id="'+gradient.id+'"]').click();const stop=page.locator('[data-stop]').first();await stop.scrollIntoViewIfNeeded();const stopBefore=(await state()).palette;box=await stop.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+45,box.y,{steps:5});assert.equal((await state()).gesture,true);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.mouse.up();await page.waitForTimeout(60);assert.deepEqual((await state()).palette,stopBefore);assert.equal((await state()).gesture,false);ok('Gradient gesture blur cancels without writes');
  await navigate('palette','curve');await page.locator('[data-cv-field=interpolation]').selectOption('bezier',{force:true});await page.locator('[data-save]').click();const curveHandle=page.locator('[data-cv-handle=out]').first();await curveHandle.scrollIntoViewIfNeeded();const curvesBefore=(await state()).curve;box=await curveHandle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+30,box.y+10,{steps:5});assert.equal((await state()).gesture,true);await curveHandle.dispatchEvent('lostpointercapture',{pointerId:1});await page.mouse.up();assert.deepEqual((await state()).curve,curvesBefore);assert.equal((await state()).gesture,false);ok('Curve capture loss restores draft');
  box=await curveHandle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+25,box.y+12);await curveHandle.evaluate(el=>window.oldHandle=el);await page.evaluate(()=>window.postMessage({type:'lomond-reference-request-exit'},'*'));await page.waitForFunction(()=>ReferenceState().exited);await page.mouse.up();await page.evaluate(()=>window.oldHandle.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:1,clientX:250,clientY:250})));await page.waitForTimeout(40);assert.deepEqual((await state()).curve,curvesBefore);assert.equal((await state()).exited,true);assert.deepEqual((await state()).subscriptions,[0,0,0,0]);ok('Active-gesture exit cancels pending work and disposes all fixture subscriptions');
  const combinations=[{width:720,height:700,theme:'dark',lang:'en',scale:'.92'},{width:420,height:600,theme:'light',lang:'zh-CN',scale:'1'},{width:320,height:440,theme:'dark',lang:'zh-CN',scale:'1.18'},{width:420,height:420,theme:'light',lang:'en',scale:'.62'}];
  for(const c of combinations){await page.setViewportSize({width:c.width,height:c.height});await fresh();await page.locator('.ref-setup').evaluate(el=>el.open=true);await page.locator('select[data-theme]').selectOption(c.theme,{force:true});await page.locator('[data-locale]').selectOption(c.lang,{force:true});await page.locator('.ref-setup').evaluate(el=>el.open=true);await page.locator('[data-scale]').selectOption(String(Number(c.scale)),{force:true});if(c.height<500)await page.locator('.ref-setup').evaluate(el=>el.open=false);for(const [route,variant]of [['registry','kit'],['settings',null],['vela',null],['palette','palette'],['palette','curve']]){await navigate(route,variant);if(route==='palette'&&variant==='palette'&&!await page.locator('.pal-detail').isVisible())await page.locator('[data-pal-action=open]').first().click();if(route==='palette'&&variant==='curve'&&!await page.locator('.cv-detail').isVisible())await page.locator('[data-cv-action=open]').first().click();const shape=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,font:getComputedStyle(document.documentElement).fontFamily,surface:getComputedStyle(document.querySelector('#reference-root')).backgroundColor,foreground:getComputedStyle(document.documentElement).color,zoom:getComputedStyle(document.querySelector('#reference-root')).zoom,height:document.querySelector('.ref-page').clientHeight,scrolls:[...document.querySelectorAll('.reg-body,.reg-form,.pal-detail,.cv-detail,.ref-transcript')].map(e=>({height:e.clientHeight,scroll:e.scrollHeight}))}));assert.ok(shape.width<=c.width+1,JSON.stringify({c,route,shape}));assert.ok(shape.height>60);if(route==='settings'){await page.locator('[data-reg-preview]').click();await page.locator('[data-reg-search]').fill('motion.curve');await page.locator('.reg-curve-graph').first().scrollIntoViewIfNeeded();}if(route==='vela'){await page.locator('[data-vela-state]').selectOption('partial',{force:true});}if(route==='palette'&&c.lang==='zh-CN'){const title=page.locator(variant==='palette'?'[data-pal-field=palette-name]':'[data-cv-field=name]');await title.fill('暮色海风 · 中文长名称与 Motion 参考');await title.blur();}await page.screenshot({path:root+'/.tmp/vela-evidence/0.3.13-b/f3/'+route+'-'+(variant||'page')+'-'+c.width+'x'+c.height+'.png'});results.push({matrix:c,route,variant,shape});}}
  ok('Representative 320/420/720, short height, themes, languages and actual scale range');
  await page.setViewportSize({width:720,height:700});await fresh();await navigate('palette');await page.evaluate(()=>{for(const sheet of document.styleSheets)for(let i=sheet.cssRules.length-1;i>=0;i--){const r=sheet.cssRules[i];if(r.constructor.name==='CSSContainerRule'||r.selectorText?.includes(':has('))sheet.deleteRule(i);}});assert.ok(await page.locator('.pal-library').isVisible());assert.ok(await page.locator('.pal-detail').isVisible());await page.setViewportSize({width:320,height:440});await page.waitForFunction(()=>document.querySelector('#reference-root').dataset.paletteWide==='false');assert.ok(await page.locator('.pal-library').isVisible());assert.equal(await page.locator('.pal-detail').isVisible(),false);ok('Explicit CEP layout fallback with container and :has rules removed');
  await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-pal-action=open]').first().click();await page.locator('[data-pal-action=open-color]').click();await page.waitForTimeout(200);assert.equal(await page.locator('.color-picker-panel').evaluate(el=>getComputedStyle(el).transform),'none');await page.keyboard.press('Escape');await page.waitForTimeout(200);assert.equal(await page.locator('.color-picker-layer').count(),0);ok('Reduced motion closes and removes popover');await page.setViewportSize({width:420,height:600});await fresh();await page.locator('[data-reg-action=createFeatureStack]').click();await page.locator('[data-exit]').click();await page.locator('[data-answer=discard]').click();await page.waitForTimeout(500);assert.equal((await state()).exited,true);assert.deepEqual((await state()).subscriptions,[0,0,0,0]);ok('Pending Registry timer cannot render or steal focus after disposal');
  assert.deepEqual(errors,[]);assert.equal(requests.some(r=>r.method!=='GET'||!r.url.startsWith(server.url)&&!r.url.startsWith('data:')),false);
  fs.writeFileSync(root+'/.tmp/vela-evidence/0.3.13-b/f3/browser-results.json',JSON.stringify({results,errors,requests},null,2));
 }catch(e){await page?.screenshot({path:root+'/.tmp/vela-evidence/0.3.13-b/f3/browser-failure.png'});fs.writeFileSync(root+'/.tmp/vela-evidence/0.3.13-b/f3/browser-failure.json',JSON.stringify({error:e.stack,errors,results},null,2));throw e;}finally{await browser.close();await server.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
