const {serve,root}=require('./server.cjs');
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
async function run(){
 const server=await serve(),browser=await chromium.launch({executablePath:process.env.UI_REFERENCE_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const results=[],errors=[],tag=process.env.F1_ENGINE||'edge';let page;
 try{
  page=await browser.newPage({viewport:{width:720,height:760}});page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.stack));
  const fresh=async()=>{await page.goto(server.url+'/client/reference/index.html');await page.locator('[data-scale]').selectOption('1',{force:true});};
  const select=async(selector,value)=>{const port=page.locator(selector);const trigger=await port.evaluateHandle(el=>el._coreSelectComponent.trigger);await trigger.asElement().scrollIntoViewIfNeeded();await trigger.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await trigger.asElement().click();await trigger.dispose();const id=await port.getAttribute('data-custom-select-id');await page.locator('[data-select-menu-for="'+id+'"] [data-value="'+value+'"]').click();};
  const nav=async(route,variant)=>{await page.locator('[data-route='+route+']').click();if(await page.locator('[data-answer=discard]').count())await page.locator('[data-answer=discard]').click();if(variant){await page.locator('[data-variant='+variant+']').click();if(await page.locator('[data-answer=discard]').count())await page.locator('[data-answer=discard]').click();}};
  const ok=name=>{results.push({name,result:'PASS'});console.log('PASS '+name);};
  await fresh();
  // Real custom portal, including native value/change and disabled options.
  await select('[data-reg-context]','noComp');assert.equal(await page.locator('[data-reg-action=createFeatureStack]').isDisabled(),true);
  await select('[data-reg-context]','text');assert.equal(await page.locator('[data-reg-context]').evaluate(el=>el._coreSelectComponent.trigger===document.activeElement),true);
  await page.locator('select[data-theme]').evaluate(el=>el._coreSelectComponent.trigger.focus());await page.keyboard.press('Enter');assert.equal(await page.locator('.select-menu.is-open').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('.select-menu.is-open').count(),0);assert.equal(await page.locator('.ref-modal').count(),0);
  await page.locator('select[data-theme]').evaluate(el=>el._coreSelectComponent.trigger.focus());await page.keyboard.press('ArrowDown');assert.equal(await page.locator('select[data-theme]').inputValue(),'light');await page.keyboard.press('ArrowUp');
  assert.equal(await page.locator('.reg-body').evaluate(el=>getComputedStyle(el,'::-webkit-scrollbar').width),'8px');ok('Custom select portal, arrows, Escape, focus restoration, value/change and scrollbar fallback');
  await nav('registry','controls');await page.locator('[data-reg-search]').fill('defaultCurve');
  for(const scale of ['.62','.92','1','1.18']){await page.locator('[data-scale]').selectOption(String(Number(scale)),{force:true});const frames=await page.locator('.reg-curve-graph').evaluate(async svg=>{const rows=[];for(let i=0;i<45;i++){await new Promise(requestAnimationFrame);rows.push({layout:svg.parentElement.clientWidth,box:svg.viewBox.baseVal.width,visual:svg.getBoundingClientRect().width});}return rows;});assert.ok(frames.slice(5).every(r=>Math.abs(r.layout-r.box)<2),JSON.stringify({scale,frames}));assert.ok(Math.max(...frames.slice(10).map(r=>r.box))-Math.min(...frames.slice(10).map(r=>r.box))<2);results.push({scale,frames});}
  await page.locator('[data-scale]').selectOption('1',{force:true});await page.locator('[data-reg-search]').fill('');ok('SVG first-open/search sizes stay in HTML layout coordinates at every scale');
  const n=page.locator('[data-reg-value=numberValue]');await n.scrollIntoViewIfNeeded();let before=await n.inputValue();await n.click();assert.deepEqual(await n.evaluate(el=>[el.selectionStart,el.selectionEnd]),[0,before.length]);await n.fill('-.');assert.equal(await n.getAttribute('aria-invalid'),'true');assert.equal((await page.evaluate(()=>ReferenceState())).values.values.numberValue,Number(before));await n.press('Escape');assert.equal(await n.inputValue(),before);
  const drag=async(input,dx,end='up')=>{await input.scrollIntoViewIfNeeded();await input.evaluate(el=>el.blur());const b=await input.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+dx,b.y+b.height/2,{steps:4});if(end==='blur')await page.evaluate(()=>window.dispatchEvent(new Event('blur')));if(end==='cancel')await input.dispatchEvent('pointercancel',{pointerId:1});if(end==='lost')await input.dispatchEvent('lostpointercapture',{pointerId:1});await page.mouse.up();};
  await drag(n,16);assert.equal(Number(await n.inputValue()),Number(before)+2);await n.click();await n.press('ArrowDown');await n.press('Enter');assert.equal(Number(await n.inputValue()),Number(before)+1);before=await n.inputValue();for(const end of ['blur','cancel','lost']){await drag(n,40,end);assert.equal(await n.inputValue(),before);assert.equal(await n.evaluate(el=>el.classList.contains('is-dragging-number')),false);}
  const rangeNumber=page.locator('[data-reg-value=rangeValue][data-reference-number]');await rangeNumber.click();await rangeNumber.fill('35');await rangeNumber.press('Enter');assert.equal(await page.locator('[data-reg-value=rangeValue][type=range]').inputValue(),'35');await n.scrollIntoViewIfNeeded();await n.evaluate(el=>el.blur());const finalBox=await n.boundingBox(),finalX=finalBox.x+finalBox.width/2;await page.mouse.move(finalX,finalBox.y+finalBox.height/2);await page.mouse.down();await n.dispatchEvent('pointermove',{pointerId:1,clientX:finalX+8,bubbles:true});await n.dispatchEvent('pointerup',{pointerId:1,clientX:finalX+24,bubbles:true});await page.mouse.up();assert.equal(Number(await n.inputValue()),Number(before)+3);
  ok('Legacy number click/select-all, horizontal scrub, step, draft, Escape, range sync and all gesture cancellations');
  await nav('settings');await page.locator('[data-reg-search]').fill('layout.scale');const setting=page.locator('[data-reg-value="layout.scale"][data-reference-number]');const oldSetting=Number(await setting.inputValue());await drag(setting,16);assert.equal(Number(await setting.inputValue()),Number((oldSetting+.02).toFixed(2)));ok('Settings consumes the shared numeric interaction');
  await nav('palette');const opacity=page.locator('[data-pal-field=solid-opacity]');const oldOpacity=await opacity.inputValue();await drag(opacity,-16);assert.equal(Number(await opacity.inputValue()),Number(oldOpacity)-2);await opacity.click();await opacity.fill('10');await opacity.press('Escape');assert.equal(Number(await opacity.inputValue()),Number(oldOpacity)-2);
  await page.locator('[data-pal-action=open-color]').click();await page.locator('.cp-channel-details summary').click();const channel=page.locator('[data-cp-channel=v][data-reference-number]');const oldChannel=await channel.inputValue();await drag(channel,-16);assert.equal(Number(await channel.inputValue()),Number(oldChannel)-2);await page.keyboard.press('Escape');ok('Palette and Picker numeric channels share drag/edit/cancel without asset persistence');
  await nav('palette','curve');assert.equal(await page.locator('[data-cv-field=out-t]').count(),0);await page.locator('.cv-advanced>summary').click();await select('[data-cv-field=interpolation]','bezier');const handle=page.locator('[data-cv-handle=out]');await handle.scrollIntoViewIfNeeded();await handle.press('Enter');assert.equal(await page.locator('[data-cv-parameter=out]').getAttribute('class'),'is-selected');
  const ht=page.locator('[data-cv-field=out-t]');await ht.fill('40');await ht.press('Enter');assert.equal(await ht.evaluate(el=>el.classList.contains('is-editing-number')),false);let curve=(await page.evaluate(()=>ReferenceState())).curve.curves[0];assert.equal(curve.nodes[0].out[0],.4);assert.match(await page.locator('[data-cv-handle=out]').getAttribute('aria-valuetext'),/40/);await page.locator('[data-cv-handle=out]').press('ArrowRight');assert.equal(Number(await ht.inputValue()),40.5);
  await ht.scrollIntoViewIfNeeded();const oldHandle=Number(await ht.inputValue());await drag(ht,16);assert.equal(Number(await ht.inputValue()),Number((oldHandle+.2).toFixed(1)));const duration=page.locator('[data-cv-field=duration]');const oldDuration=Number(await duration.inputValue());await drag(duration,16);assert.equal(Number(await duration.inputValue()),oldDuration+20);ok('Curve selection, separate handle parameters, model/graph/numeric feedback and preview duration');
  // A detached numeric control must not retain an active gesture listener.
  await duration.evaluate(el=>el.blur());let b=await duration.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+24,b.y+b.height/2);await duration.evaluate(el=>window.oldNumber=el);await page.evaluate(()=>window.postMessage({type:'lomond-reference-request-exit'},'*'));if(await page.locator('[data-answer=discard]').count())await page.locator('[data-answer=discard]').click();await page.mouse.up();assert.equal(await page.evaluate(()=>ReferenceState().exited),true);const disposed=await page.evaluate(()=>ReferenceState().curve);await page.evaluate(()=>oldNumber.dispatchEvent(new PointerEvent('pointermove',{pointerId:1,bubbles:true,clientX:800})));assert.deepEqual(await page.evaluate(()=>ReferenceState().curve),disposed);assert.equal(await page.locator('.select-menu').count(),0);ok('Active numeric disposal cancels and removes all select portals');
  await fresh();await select('[data-locale]','zh-CN');await nav('registry','controls');await page.locator('[data-reg-search]').fill('defaultCurve');assert.match(await page.locator('.reg-curve-gesture').innerText(),/拖动/);assert.match(await page.locator('[data-reg-handle]').first().getAttribute('aria-label'),/控制点/);await page.locator('[data-reg-search]').fill('no-such-control');assert.match(await page.locator('.reg-empty').innerText(),/未找到/);await nav('palette');await page.locator('[data-pal-field=palette-name]').fill('Keep My Asset');await page.locator('[data-pal-field=palette-name]').blur();assert.equal(await page.locator('[data-pal-field=palette-name]').inputValue(),'Keep My Asset');await page.locator('[data-pal-action=open-color]').click();assert.equal(await page.locator('.cp-header h4').innerText(),'颜色选择器');await page.locator('[data-cp-field=hex]').fill('oops');await page.locator('[data-cp-field=hex]').press('Enter');assert.match(await page.locator('.cp-status').innerText(),/请输入/);await page.keyboard.press('Escape');await nav('palette','curve');assert.match(await page.locator('.cv-parameter-area').innerText(),/端点|手柄/);assert.match(await page.locator('.cv-preview-settings').innerText(),/毫秒|时长/);await nav('vela');assert.equal(await page.locator('[data-isolated-command=approve]').innerText(),'批准');await nav('settings');await page.locator('[data-reg-search]').fill('shadow');assert.ok(!/ · (offsetX|offsetY|alpha|blur|spread)/.test(await page.locator('.reg-sections').innerText()));assert.doesNotMatch(await page.locator('body').innerText(),/\$\{copy|reference\.ui\./);ok('Chinese dynamic controls, errors, handles, settings parts and unchanged asset names');
  await fresh();await page.locator('.ref-diagnostics').evaluate(el=>el.open=true);await page.locator('[data-size-probe]').click();await nav('palette');await page.locator('[data-pal-action=open-color]').click();await page.waitForFunction(()=>!document.querySelector('[data-size-probe]').disabled);const evidence=JSON.parse(await page.locator('[data-size-evidence] textarea').inputValue());assert.ok(evidence.rows.length<=180&&evidence.rows.length>1);assert.ok(evidence.rows.some(r=>r.panel));assert.ok(evidence.rows.every(r=>r.instances<=1));ok('User-triggered bounded size sampling, no duplicate Picker instance');
  await fresh();await nav('palette');
  for(const scale of [.62,1.18]){await page.locator('[data-scale]').selectOption(String(scale),{force:true});if(!await page.locator('.pal-detail').isVisible())await page.locator('[data-pal-action=open]').first().evaluate(el=>el.click());await page.locator('[data-pal-action=open-color]').scrollIntoViewIfNeeded();await page.locator('[data-pal-action=open-color]').evaluate(el=>el.click());await page.waitForTimeout(380);await page.locator('[data-cp-axis=hsv-v]').evaluate(el=>el.click());const box=await page.locator('[data-cp-plane]').evaluate(el=>{const r=el.getBoundingClientRect(),f=innerWidth/document.querySelector('#reference-root').getBoundingClientRect().width;return {x:r.x*f,y:r.y*f,w:r.width*f,h:r.height*f};});await page.mouse.click(box.x+box.w*.25,box.y+box.h*.75);assert.ok(Math.abs(Number(await page.locator('[data-cp-channel=h][data-reference-number]').inputValue())-90)<=1);assert.ok(Math.abs(Number(await page.locator('[data-cp-channel=s][data-reference-number]').inputValue())-25)<=1);await page.keyboard.press('Escape');await page.waitForTimeout(260);await page.locator('select[data-theme]').evaluate(el=>el._coreSelectComponent.trigger.click());const port=await page.locator('select[data-theme]').evaluate(el=>{const c=el._coreSelectComponent,r=c.trigger.getBoundingClientRect(),f=innerWidth/document.querySelector('#reference-root').getBoundingClientRect().width,m=c.menu.getBoundingClientRect();return {bottom:r.bottom*f,menuTop:m.top,menuRight:m.right};});assert.ok(Math.abs(port.menuTop-port.bottom-6)<2,JSON.stringify({scale,port}));assert.ok(port.menuRight<=720);await page.keyboard.press('Escape');}
  ok('Physical pointer and portal anchoring use viewport coordinates at non-1 scale');
  assert.deepEqual(errors,[]);fs.writeFileSync(root+'/.tmp/vela-evidence/0.3.13-b/f3/'+tag+'-results.json',JSON.stringify({ua:await page.evaluate(()=>navigator.userAgent),results,errors},null,2));
 }catch(e){await page?.screenshot({path:root+'/.tmp/vela-evidence/0.3.13-b/f3/'+tag+'-failure.png'});fs.writeFileSync(root+'/.tmp/vela-evidence/0.3.13-b/f3/'+tag+'-failure.json',JSON.stringify({error:e.stack,results,errors},null,2));throw e;}finally{await browser.close();await server.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
