const {serve,root}=require('./server.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict'),fs=require('node:fs');
const raw=root+'/.tmp/vela-evidence/0.3.13-b/f3';fs.mkdirSync(raw,{recursive:true});
async function run(){const server=await serve(),browser=await chromium.launch({executablePath:process.env.UI_REFERENCE_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,ignoreDefaultArgs:['--hide-scrollbars']});let page;const results=[],errors=[],engine=process.env.F2_ENGINE||'edge';
try{page=await browser.newPage({viewport:{width:720,height:900}});page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.stack));
const click=selector=>page.locator(selector).first().evaluate(e=>e.click());
const select=(selector,value)=>page.locator('select'+selector).selectOption(value,{force:true});
const nav=async(route,variant)=>{await click('[data-route='+route+']');if(await page.locator('[data-answer=discard]').count())await click('[data-answer=discard]');if(variant){await click('[data-variant='+variant+']');if(await page.locator('[data-answer=discard]').count())await click('[data-answer=discard]');}};
const fresh=async()=>{await page.goto(server.url+(process.env.F2_BEFORE?'/.tmp/vela-evidence/0.3.13-b/f2/before/index.html':'/client/reference/index.html'));await select('[data-scale]','1');};
const ok=name=>{results.push({name,result:'PASS'});console.log('PASS '+name);};
const atRest=async()=>{const samples=await page.locator('[data-cv-field=playhead]').evaluate(async el=>{const r=[];for(let i=0;i<15;i++){await new Promise(requestAnimationFrame);r.push(el.value);}return r;});assert.ok(samples.every(v=>v==='0'),JSON.stringify(samples));};
const open=async index=>{await page.locator('[data-cv-action=open]').nth(index).evaluate(e=>e.click());await atRest();};
await fresh();await nav('palette','curve');
if(process.env.F2_BEFORE){await page.locator('[data-cv-action=open]').first().evaluate(e=>e.click());const samples=await page.locator('[data-cv-field=playhead]').evaluate(async el=>{const r=[];for(let i=0;i<15;i++){await new Promise(requestAnimationFrame);r.push(el.value);}return r;});assert.ok(samples.some(v=>Number(v)>0),'F1 selection auto-play counterexample must reproduce');const order=await page.evaluate(()=>!!(document.querySelector('.cv-parameter-area').compareDocumentPosition(document.querySelector('.cv-preview-settings'))&Node.DOCUMENT_POSITION_FOLLOWING));assert.equal(order,true);await nav('registry','controls');await page.locator('[data-reg-search]').fill('rangeValue');const first=await page.locator('.reg-numeric').evaluate(e=>e.firstElementChild.type);assert.equal(first,'range');await page.locator('[data-reg-search]').fill('fillColor');assert.equal(await page.locator('.reg-color').evaluate(e=>e.firstElementChild.tagName),'BUTTON');fs.writeFileSync(raw+'/before-workflow.json',JSON.stringify({autoPlaySamples:samples,parametersBeforePlayback:order,rangeFirstChild:first,colorFirstChild:'BUTTON'}));console.log('F1 auto-play, ordering and compound counterexamples reproduced');return;}
await atRest();await open(0);ok('First entry and selecting a library item never play');
await click('[data-cv-action=play]');await page.waitForFunction(()=>Number(document.querySelector('[data-cv-field=playhead]').value)>0);await click('[data-cv-action=play]');await open(1);ok('Play/pause A then select B resets without playing');
await open(0);await click('[data-cv-action=play]');await page.waitForFunction(()=>Number(document.querySelector('[data-cv-field=playhead]').value)>0);await open(1);ok('Switch during playback cancels A and resets B');
await open(0);await page.locator('[data-cv-field=duration]').fill('80');await page.locator('[data-cv-field=duration]').press('Enter');await click('[data-cv-action=play]');await page.waitForFunction(()=>document.querySelector('[data-cv-field=playhead]').value==='1000');await open(1);ok('Switch after completion resets the next curve without playing');
await page.locator('[data-cv-action=open]').evaluateAll(items=>{for(const i of [0,2,1,0,2,1])items[i].click();});await atRest();await nav('registry');await nav('palette','curve');await atRest();ok('Rapid choices and leaving/returning do not inherit playback');
await open(0);await page.locator('[data-cv-field=duration]').fill('2000');await page.locator('[data-cv-field=duration]').press('Enter');await click('[data-save]');await click('[data-cv-action=play]');await select('[data-theme]','light');await page.waitForFunction(()=>Number(document.querySelector('[data-cv-field=playhead]').value)>0);await select('[data-locale]','zh-CN');await atRest();await page.locator('[data-cv-field=duration]').fill('2100');await page.locator('[data-cv-field=duration]').press('Enter');await atRest();ok('Parameter, language and theme redraws create no playback round');
assert.equal(await page.locator('[data-cv-field=point-t]').count(),0);assert.equal(await page.locator('[data-cv-parameter=in]').count(),0);assert.equal(await page.locator('.cv-advanced').getAttribute('open'),null);
const order=await page.evaluate(()=>{const a=['.cv-graph-wrap','.cv-preview-settings','.cv-parameter-area','.cv-advanced'].map(s=>document.querySelector(s));return a.slice(1).every((e,i)=>a[i].compareDocumentPosition(e)&Node.DOCUMENT_POSITION_FOLLOWING);});assert.equal(order,true);
await click('[data-cv-action=structure]');await select('[data-cv-field=interpolation]','bezier');await click('[data-element=out]');assert.equal(await page.locator('[data-cv-parameter=out]').count(),1);assert.equal(await page.locator('[data-cv-parameter=in]').count(),0);await click('[data-cv-action=add-point]');await click('[data-element=point]');assert.equal(await page.locator('[data-cv-field=point-t]').count(),1);assert.equal(await page.locator('[data-cv-field=point-v]').getAttribute('min'),'-200');assert.equal(await page.locator('[data-cv-field=point-v]').getAttribute('max'),'300');assert.equal(await page.locator('[data-cv-field=point-v]').getAttribute('step'),'0.1');assert.equal(await page.locator('[data-element=in]').count(),1);assert.equal(await page.locator('[data-element=out]').count(),1);await click('[data-element=in]');assert.equal(await page.locator('[data-cv-parameter=in]').count(),1);assert.equal(await page.locator('[data-cv-parameter=out]').count(),0);assert.equal(await page.locator('[data-cv-field=point-t]').count(),0);await select('[data-cv-field=node]','2');await click('[data-element=in]');assert.equal(await page.locator('[data-cv-field=point-t]').count(),0);assert.equal(await page.locator('[data-cv-parameter=in]').count(),1);assert.equal(await page.locator('[data-cv-parameter=out]').count(),0);await page.screenshot({path:raw+'/'+engine+'-curve-order.png'});await page.locator('.cv-advanced').evaluate(e=>e.open=false);await page.locator('.cv-detail').evaluate(e=>e.scrollTop=0);await page.screenshot({path:raw+'/'+engine+'-curve-preview-playback.png'});ok('Preview → playback → editable selection → collapsed structure, including middle and endpoint cases');
const inspectCombos=async(label)=>{const entries=await page.locator('.reference-combo').evaluateAll(groups=>groups.filter(g=>g.getClientRects().length&&g.clientWidth>0).map(g=>{const value=g.querySelector('.ref-combo-value input'),visual=g.querySelector(':scope > input[type=range],:scope > button'),v=value.getBoundingClientRect(),r=visual.getBoundingClientRect(),root=document.querySelector('#reference-root'),factor=innerWidth/root.getBoundingClientRect().width;return {kind:g.className,valueWidth:v.width*factor,visualWidth:r.width*factor,layoutValueWidth:value.offsetWidth,layoutVisualWidth:visual.offsetWidth,order:!!(value.compareDocumentPosition(visual)&Node.DOCUMENT_POSITION_FOLLOWING),wrapped:Math.abs(r.y-v.y)>12,overflow:g.scrollWidth-g.clientWidth,min:value.min,max:value.max,step:value.step};}));assert.ok(entries.length,label);for(const e of entries){assert.equal(e.order,true,label);assert.ok(e.overflow<=1,JSON.stringify({label,e}));assert.ok(e.layoutValueWidth<=160,JSON.stringify({label,e}));if(e.kind.includes('range-number'))assert.ok(e.layoutVisualWidth>=103,JSON.stringify({label,e}));}results.push({label,entries});};
for(const [width,height,scale,lang]of [[320,440,'1.18','zh-CN'],[420,740,'1','en'],[720,800,'.62','zh-CN']]){
 await page.setViewportSize({width,height});await fresh();await select('[data-locale]',lang);await select('[data-scale]',String(Number(scale)));await page.locator('.ref-setup').evaluate(e=>e.open=false);
 await nav('registry','controls');await page.locator('[data-reg-search]').fill('rangeValue');await inspectCombos('Registry Range '+width);const rangeNumber=page.locator('[data-reg-value=rangeValue][data-reference-number]');await rangeNumber.focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.matches('[data-reg-value=rangeValue][type=range]')),true);await rangeNumber.fill('35');await rangeNumber.press('Enter');assert.equal(await page.locator('[data-reg-value=rangeValue][type=range]').inputValue(),'35');
 await page.locator('[data-reg-search]').fill('fillColor');await inspectCombos('Registry Color '+width);const hex=page.locator('[data-reg-value=fillColor]');await hex.focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.matches('[data-reg-color=fillColor]')),true);
 await nav('settings');await page.locator('[data-reg-search]').fill('layout.scale');await inspectCombos('Settings Range '+width);const decimal=page.locator('[data-reg-value="layout.scale"][data-reference-number]');await decimal.fill('1.17');await decimal.press('Enter');assert.equal(await decimal.inputValue(),'1.17');assert.equal(await page.locator('[data-reg-value="layout.scale"][type=range]').inputValue(),'1.17');await page.locator('[data-reg-search]').fill('base.accent');await inspectCombos('Settings Color '+width);
 await nav('palette');if(!await page.locator('.pal-detail').isVisible())await click('[data-pal-action=open]');await inspectCombos('Palette Color '+width);const ph=page.locator('[data-pal-field=solid-hex]');await ph.focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.matches('[data-pal-action=open-color]')),true);await page.locator('[data-pal-action=open-color]').scrollIntoViewIfNeeded();await click('[data-pal-action=open-color]');await page.locator('.cp-channel-details').evaluate(e=>e.open=true);await inspectCombos('Picker Range '+width);await page.screenshot({path:raw+'/'+engine+'-combos-'+width+'.png'});await page.keyboard.press('Escape');await page.waitForTimeout(300);
}
ok('Shared compact value-first DOM/Tab order and remaining-width sliders at 320/420/720, scales and both locales');
// Bounded fixture using the real compound constructor and enhancement; it does
// not add a production field or write any model/store.
await page.evaluate(async()=>{const controls=await import('/client/reference/src/controls.js'),fixture=document.createElement('section');fixture.id='signed-combo-fixture';fixture.style.cssText='position:fixed;left:8px;top:8px;width:220px;z-index:9999';fixture.innerHTML=controls.rangeNumber('<input type="number" value="-400.125456" min="-500" max="500" step="0.000001" aria-label="signed fixture">','<input type="range" min="-500" max="500" step="0.000001" value="-400.125456" aria-label="signed fixture slider">');document.querySelector('#reference-root').append(fixture);controls.mountControls(fixture);window.disposeSigned=()=>{controls.disposeControls(fixture);fixture.remove();};});
const signed=page.locator('#signed-combo-fixture [data-reference-number]');const fit=await signed.evaluate(e=>{const s=getComputedStyle(e),ctx=document.createElement('canvas').getContext('2d');ctx.font=s.font;return {available:e.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight),required:ctx.measureText(e.value).width};});assert.ok(fit.available>=fit.required,JSON.stringify(fit));await signed.focus();await signed.press('ArrowUp');await signed.press('Enter');assert.equal(await signed.inputValue(),'-400.125455');await signed.focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.matches('#signed-combo-fixture [type=range]')),true);await inspectCombos('signed decimal fixture');await page.evaluate(()=>{disposeSigned();delete window.disposeSigned;});ok('Bounded actual-control fixture fits signed six-decimal values and preserves step/Tab semantics');
await page.setViewportSize({width:720,height:800});await fresh();await nav('palette');await page.locator('.ref-diagnostics').evaluate(e=>e.open=true);await click('[data-size-probe]');const firstHeight=await page.locator('.ref-header').evaluate(e=>e.offsetHeight);await click('[data-pal-action=open-color]');assert.equal(await page.locator('[data-size-evidence]').isHidden(),true);await page.waitForFunction(()=>!document.querySelector('[data-size-probe]').disabled);const evidence=JSON.parse(await page.locator('[data-size-evidence] textarea').inputValue());assert.ok(evidence.rows.length<=180);assert.ok(evidence.rows.some(r=>r.pickerBody&&r.pickerBody.scrollbarLayout[0]>0));assert.ok(evidence.rows.filter(r=>r.panel).every(r=>r.ancestors.length>=2));assert.equal(evidence.version,'0.3.13-b-f2');assert.ok(evidence.rows.every(r=>r.header.offset[1]===firstHeight),'diagnostic output must not alter header layout while sampling');assert.ok(evidence.rows.every(r=>r.instances<=1));fs.writeFileSync(raw+'/'+engine+'-user-sampler.json',JSON.stringify(evidence,null,2));if(await page.locator('.color-picker-layer').count())await page.keyboard.press('Escape');await page.waitForTimeout(300);await click('[data-size-probe]');await page.evaluate(()=>window.postMessage({type:'lomond-reference-request-exit'},'*'));if(await page.locator('[data-answer=discard]').count())await click('[data-answer=discard]');await page.waitForFunction(()=>ReferenceState().exited);assert.equal(await page.locator('.color-picker-layer').count(),0);assert.deepEqual(await page.evaluate(()=>ReferenceState().subscriptions),[0,0,0,0]);ok('Bounded in-memory sampler includes real gutters/ancestors and is cancelled on exit');
assert.deepEqual(errors,[]);fs.writeFileSync(raw+'/'+engine+'-f2-results.json',JSON.stringify({ua:await page.evaluate(()=>navigator.userAgent),results,errors},null,2));
}catch(e){await page?.screenshot({path:raw+'/'+engine+'-f2-failure.png'});fs.writeFileSync(raw+'/'+engine+'-f2-failure.json',JSON.stringify({error:e.stack,results,errors},null,2));throw e;}finally{await browser.close();await server.close();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
