// Rendered counterexamples for F3; immutable v26 is evidence, not a dependency of production.
const {serve,root}=require('./server.cjs');const {chromium}=require('playwright');const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path'),vm=require('node:vm');
const raw=root+'/.tmp/vela-evidence/0.3.13-b/f3';fs.mkdirSync(raw,{recursive:true});
const engine=process.env.F3_ENGINE||'edge';
async function run(){const server=await serve(),browser=await chromium.launch({executablePath:process.env.UI_REFERENCE_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,ignoreDefaultArgs:['--hide-scrollbars']});const results=[],errors=[];let page;
try{
 page=await browser.newPage({viewport:{width:420,height:800}});page.on('pageerror',e=>errors.push(e.stack));
 const click=s=>page.locator(s).first().evaluate(e=>e.click()),select=(s,v)=>page.locator('select'+s).selectOption(v,{force:true});
 const nav=async(route,variant)=>{await click('[data-route='+route+']');if(await page.locator('[data-answer=discard]').count())await click('[data-answer=discard]');if(variant){await click('[data-variant='+variant+']');if(await page.locator('[data-answer=discard]').count())await click('[data-answer=discard]');}};
 const metric=async selector=>page.locator(selector).first().evaluate(g=>{const value=g.querySelector('.ref-combo-value'),input=value.querySelector('input'),visual=g.querySelector(':scope > input[type=range],:scope > button'),a=value.getBoundingClientRect(),b=visual.getBoundingClientRect(),r=g.getBoundingClientRect(),root=document.querySelector('#reference-root'),k=innerWidth/root.getBoundingClientRect().width;return {width:a.width*k,edge:(a.right-r.left)*k,start:(b.left-r.left)*k,gap:(b.left-a.right)*k,wrapped:Math.abs(a.y-b.y)*k>20,visualWidth:visual.offsetWidth,overflow:g.scrollWidth-g.clientWidth,order:!!(input.compareDocumentPosition(visual)&Node.DOCUMENT_POSITION_FOLLOWING)};});
 await page.goto(server.url+'/.tmp/vela-evidence/0.3.13-b/f3/before/index.html');await select('[data-scale]','1');await nav('registry','controls');await page.locator('[data-reg-search]').fill('rangeValue');const beforeNumber=await metric('.ref-range-number');await page.locator('[data-reg-search]').fill('fillColor');const beforeColor=await metric('.ref-color-control');assert.ok(Math.abs(beforeNumber.edge-beforeColor.edge)>5);await nav('vela');assert.equal(await page.locator('.settings-slot svg').count(),0);results.push({counterexample:'F2 unequal columns and missing source settings SVG',beforeNumber,beforeColor});
 const beforeMask=await page.locator('.ref-runtime-detail summary').evaluate(e=>getComputedStyle(e,'::before').webkitMaskImage);results.push({beforeMask});
 const source=fs.readFileSync(path.join(root,'.tmp/vela-evidence/0.3.13-b/lab-source/dist/app.js'),'utf8'),icons=vm.runInNewContext('('+source.match(/const icons=(\{[^]*?\});/)[1]+')');
 for(const [width,height,scale,lang,theme]of [[420,800,'1','en','dark'],[320,440,'1.18','zh-CN','light'],[720,820,'0.62','zh-CN','dark']]){
  await page.setViewportSize({width,height});await page.goto(server.url+'/client/reference/index.html');await select('[data-scale]',scale);await select('[data-locale]',lang);await select('[data-theme]',theme);await page.locator('.ref-setup').evaluate(e=>e.open=false);
  for(const [route,variant,numberKey,colorKey]of [['registry','controls','rangeValue','fillColor'],['settings',null,'layout.scale','base.accent']]){
   await nav(route,variant);await page.locator('[data-reg-search]').fill(numberKey);const n=await metric('.ref-range-number');const input=page.locator('[data-reference-number]').first();await input.fill(route==='settings'?'1.18':'35');await input.press('Enter');const changed=await metric('.ref-range-number');assert.deepEqual(changed,n,'live value must not move column');await page.locator('[data-reg-search]').fill(colorKey);const c=await metric('.ref-color-control');assert.ok(Math.abs(n.width-c.width)<.1,JSON.stringify({n,c}));assert.ok(Math.abs(n.edge-c.edge)<.1);if(!n.wrapped&&!c.wrapped)assert.ok(Math.abs(n.start-c.start)<.1);assert.ok(n.visualWidth>=104);assert.ok(n.order&&c.order);assert.ok(n.overflow<=1&&c.overflow<=1);results.push({route,width,height,scale,lang,theme,n,c});
  }
  await nav('palette');if(!await page.locator('.pal-detail').isVisible())await click('[data-pal-action=open]');const palette=await metric('.ref-color-control');assert.ok(Math.abs(palette.width-128*Number(scale))<1);await page.locator('[data-pal-action=open-color]').scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await click('[data-pal-action=open-color]');await page.locator('.cp-channel-details').evaluate(e=>e.open=true);await page.waitForFunction(()=>document.querySelector('.color-picker-panel')?.style.opacity==='1');const channel=await metric('.cp-channel .ref-range-number');assert.ok(Math.abs(palette.width-channel.width)<.1);assert.ok(channel.visualWidth>=104);await page.screenshot({path:raw+'/'+engine+'-compound-'+width+'.png'});await page.keyboard.press('Escape');await page.waitForTimeout(350);
  await nav('vela');await select('[data-vela-state]','partial');const projection=await page.locator('.ref-projection').innerText();assert.match(projection,/committed-target/);for(const name of ['vela','plus','settings','check','send']){const svg=page.locator('[data-lab-icon='+name+']').first();assert.equal(await svg.getAttribute('viewBox'),'0 0 24 24');assert.equal(await svg.getAttribute('stroke-width'),'1.5');assert.equal(await svg.getAttribute('fill'),'none');const expected=await page.evaluate(markup=>{const el=document.createElementNS('http://www.w3.org/2000/svg','svg');el.innerHTML=markup;return el.innerHTML;},icons[name]);assert.equal(await svg.innerHTML(),expected);}
  await select('[data-vela-state]','executing');assert.equal(await page.locator('[data-vela-send] [data-lab-icon=stop]').count(),1);await click('[data-vela-send]');assert.equal(await page.locator('select[data-vela-state]').inputValue(),'executing');await select('[data-vela-state]','review');const before=await page.locator('.ref-projection').innerText();await click('[data-isolated-command=new]');assert.equal(await page.locator('.ref-projection').innerText(),before,'new command remains isolated');await click('[data-vela-appearance]');assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('select[data-theme]').parentElement.querySelector('.select-trigger')),true);await page.locator('.ref-setup').evaluate(e=>e.open=false);
  await select('[data-locale]',lang==='en'?'zh-CN':'en');if(await page.locator('[data-answer=discard]').count())await click('[data-answer=discard]');assert.equal(await page.locator('[data-lab-icon=settings]').count(),1);await select('[data-theme]',theme==='dark'?'light':'dark');assert.equal(await page.locator('[data-lab-icon=plus]').count(),1);
  const mask=await page.locator('.ref-runtime-detail summary').evaluate(e=>getComputedStyle(e,'::before').webkitMaskImage);assert.match(mask,/data:image\/svg\+xml/);await page.screenshot({path:raw+'/'+engine+'-icons-vela-'+width+'.png'});
  await nav('palette','curve');const paths=await page.locator('.cv-mini-guide').count();assert.ok(paths>0);await nav('registry','controls');await page.locator('[data-reg-search]').fill('defaultCurve');assert.ok(await page.locator('.reg-curve-graph path').count()>0);await page.screenshot({path:raw+'/'+engine+'-icons-registry-'+width+'.png'});
 }
 // Long signed decimals and units share the group-wide expansion contract. This
 // imports the actual constructor/enhancement; no duplicated behavior or Store.
 await page.goto(server.url+'/client/reference/index.html');await select('[data-scale]','1');await page.evaluate(async()=>{const c=await import('/client/reference/src/controls.js'),group=document.createElement('section');group.id='f3-fixture';group.style.cssText='position:absolute;inset:0 auto auto 0;width:300px;z-index:9999;background:var(--surface);--ref-combo-column:9rem';group.innerHTML=c.rangeNumber('<input type="number" min="-500" max="500" step="0.000001" value="-400.125456" aria-label="signed value">','<input type="range" min="-500" max="500" step="0.000001" aria-label="signed range">')+c.colorControl('<input value="#B5ADE9FF" aria-label="hex">','<button aria-label="picker">Color</button>');document.querySelector('#reference-root').append(group);c.mountControls(group);window.disposeF3=()=>{c.disposeControls(group);group.remove();};});
 const longN=await metric('#f3-fixture .ref-range-number'),longC=await metric('#f3-fixture .ref-color-control');assert.deepEqual([longN.edge,longN.start],[longC.edge,longC.start]);const fit=await page.locator('#f3-fixture input').first().evaluate(e=>{const s=getComputedStyle(e),ctx=document.createElement('canvas').getContext('2d');ctx.font=s.font;return {required:ctx.measureText(e.value).width,available:e.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight)};});assert.ok(fit.required<=fit.available);await page.locator('#f3-fixture').evaluate(e=>e.style.width='190px');assert.equal((await metric('#f3-fixture .ref-range-number')).wrapped,true);await page.evaluate(()=>{disposeF3();delete window.disposeF3;});results.push({groupExpansion:{longN,longC,fit}});
 assert.deepEqual(errors,[]);fs.writeFileSync(raw+'/'+engine+'-f3-results.json',JSON.stringify({results,errors},null,2));console.log('PASS F3 columns: actual edges/value changes/group expansion/wrapping; exact v26 SVG, masked disclosures, lifecycle, themes/locales/scales.');
}catch(e){await page?.screenshot({path:raw+'/'+engine+'-f3-failure.png'});fs.writeFileSync(raw+'/'+engine+'-f3-failure.json',JSON.stringify({error:e.stack,results,errors},null,2));throw e;}finally{await browser.close();await server.close();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
