// Pixel evidence, not CSS.supports/UA acceptance. Uses the unchanged v26 source
// and actual embedded sandbox. Patterned scroll content is explicitly a fixture.
const {serve,root}=require('./server.cjs');const {chromium}=require('playwright');const {PNG}=require('playwright-core/lib/utilsBundle');const fs=require('node:fs'),assert=require('node:assert/strict');
const {environment}=require('./f4-mechanism.cjs');const raw=root+'/.tmp/vela-evidence/0.3.13-b/f4',engine=process.env.F4_ENGINE||'edge';fs.mkdirSync(raw,{recursive:true});
async function run(){const server=await serve(),browser=await chromium.launch({executablePath:process.env.UI_REFERENCE_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,ignoreDefaultArgs:['--hide-scrollbars']});const rows=[],errors=[];let env;
try{for(const theme of ['dark','light'])for(const scale of ['1','0.62','1.18'])for(const kind of ['source','reference','iframe']){
 const page=await browser.newPage({viewport:{width:kind==='source'?1200:420,height:1100}});page.on('pageerror',e=>errors.push(e.stack));if(!env)env=await environment(browser,page);await page.goto(server.url+(kind==='source'?'/lab/index.html':kind==='iframe'?'/client/launcher-fixture':'/client/reference/index.html'));let surface=page;
 if(kind==='iframe'){await page.locator('#launch').click();await page.waitForSelector('iframe');surface=page.frames().find(f=>f.parentFrame());await surface.waitForSelector('[data-route=vela]');assert.equal(await page.locator('iframe').getAttribute('sandbox'),'allow-scripts');}
 if(kind!=='source'){await surface.locator('select[data-scale]').selectOption(scale,{force:true});await surface.locator('select[data-theme]').selectOption(theme,{force:true});await surface.locator('[data-route=vela]').evaluate(e=>e.click());}else{await page.locator('.theme-control [data-theme='+theme+']').click();}
 const shell=surface.locator('.vela-shell').first();
 // Equal shell and effect geometry for rendering comparison only. No production
 // code or actual captured facts are replaced; a separate probe document is used.
 await shell.evaluate((el,{scale,kind})=>{el.style.width='400px';el.style.flex='0 0 450px';el.style.height='450px';el.style.setProperty('--composer-height','126px','important');el.style.setProperty('--composer-fade','48px','important');if(kind==='source'){el.closest('.plugin').style.height='850px';el.closest('.plugin').style.zoom=scale;}const m=el.querySelector('.messages');m.innerHTML='<p>BLUR RENDER FIXTURE / 模糊渲染反例</p>'+Array.from({length:80},(_,i)=>'<div data-blur-pattern style="height:24px;position:relative;background:linear-gradient(90deg,#222 0 50%,#ddd 50% 100%) left/50% 100% no-repeat,repeating-linear-gradient(90deg,#222 0 3px,#ddd 3px 6px) right/50% 100% no-repeat"><span style="position:absolute;left:50%;width:18%;overflow:hidden;white-space:nowrap;color:red">Evidence '+i+' 事实</span></div>').join('');},{scale,kind});
 await surface.addStyleTag({content:'.vela-shell{--composer-height:126px!important;--composer-fade:48px!important}'});
 for(const scroll of [120,157]){
  await shell.locator('.messages').evaluate((e,y)=>e.scrollTop=y,scroll);await surface.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const info=await shell.evaluate((el,kind)=>{const root=document.querySelector('#reference-root'),k=root?innerWidth/root.getBoundingClientRect().width:(getComputedStyle(el.closest('.plugin')).zoom==='1'?1:NaN),s=el.getBoundingClientRect(),h=el.querySelector('.composer-haze').getBoundingClientRect(),c=el.querySelector('.composer').getBoundingClientRect(),calibrated=Number.isFinite(k)?k:1;return {shell:{x:s.x,y:s.y,w:s.width,h:s.height},haze:{x:h.x,y:h.y,w:h.width,h:h.height},composer:{x:c.x,y:c.y,w:c.width,h:c.height},k:calibrated,layers:[...el.querySelectorAll('.composer-haze>span')].map(e=>{const s=getComputedStyle(e);return {blur:s.backdropFilter,mask:s.webkitMaskImage,opacity:s.opacity}}),veil:getComputedStyle(el.querySelector('.composer-haze'),'::after').backgroundImage,ancestors:(()=>{const a=[];for(let e=el;e;e=e.parentElement){const s=getComputedStyle(e);a.push({tag:e.tagName,class:e.className,filter:s.filter,backdrop:s.backdropFilter,mask:s.webkitMaskImage,opacity:s.opacity,overflow:s.overflow,isolation:s.isolation,zoom:s.zoom,transform:s.transform});}return a;})()};},kind);
  // Whole-viewport screenshots avoid old Chromium's pre-zoom DOMRect clipping.
  const name=engine+'-'+kind+'-'+theme+'-'+scale+'-'+scroll;
  const on=PNG.sync.read(await page.screenshot({path:raw+'/'+name+'-blur.png'}));
  await shell.locator('.composer-haze>span').evaluateAll(nodes=>nodes.forEach(e=>e.style.setProperty('backdrop-filter','none','important')));
  const off=PNG.sync.read(await page.screenshot({path:raw+'/'+name+'-gradient-only.png'}));await shell.locator('.composer-haze>span').evaluateAll(nodes=>nodes.forEach(e=>e.style.removeProperty('backdrop-filter')));
  let k=info.k;if(kind==='source'){
   // The source plugin has a known explicit 400px shell, so this calibration
   // uses a layout invariant, not UA detection.
   k=400*Number(scale)/info.shell.w;
  }
  const frameOffset=kind==='iframe'?await page.locator('iframe').boundingBox():{x:0,y:0};const rect={x:Math.round(info.haze.x*k+frameOffset.x),y:Math.round(info.haze.y*k+frameOffset.y),w:Math.round(info.haze.w*k),h:Math.round(info.haze.h*k)};
  await page.screenshot({path:raw+'/'+name+'-shell.png',clip:{x:info.shell.x*k+frameOffset.x,y:info.shell.y*k+frameOffset.y,width:info.shell.w*k,height:info.shell.h*k}});
  const band=(from,to)=>{let sum=0,count=0;for(let y=rect.y+Math.round(from*Number(scale));y<rect.y+Math.round(to*Number(scale));y++)for(let x=rect.x+Math.round(rect.w*.7);x<rect.x+Math.round(rect.w*.88);x++){if(x<0||y<0||x>=on.width||y>=on.height)continue;const i=(y*on.width+x)*4;sum+=Math.abs(on.data[i]-off.data[i])+Math.abs(on.data[i+1]-off.data[i+1])+Math.abs(on.data[i+2]-off.data[i+2]);count+=3;}return sum/count;};
  // Inspect edge diffusion separately with only the foreground controls hidden.
  // The same real background and unchanged surface veil remain; no mirroring.
  await shell.locator('.composer').evaluate(e=>e.style.visibility='hidden');
  const detailOn=PNG.sync.read(await page.screenshot());await shell.locator('.composer-haze>span').evaluateAll(nodes=>nodes.forEach(e=>e.style.setProperty('backdrop-filter','none','important')));const detailOff=PNG.sync.read(await page.screenshot());await shell.locator('.composer-haze>span').evaluateAll(nodes=>nodes.forEach(e=>e.style.removeProperty('backdrop-filter')));await shell.locator('.composer').evaluate(e=>e.style.removeProperty('visibility'));
  const pattern=await shell.locator('[data-blur-pattern]').first().evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,w:r.width};});const px=pattern.x*k+frameOffset.x,pw=pattern.w*k;
  const detail=[];for(const fraction of [.04,.22,.46,.66]){const y0=Math.round(rect.y+rect.h*fraction),y1=y0+Math.max(3,Math.round(6*Number(scale))),center=px+pw*.25,left=Math.round(px+pw*.08),right=Math.round(px+pw*.42);const profile=img=>{const p=[];for(let x=left;x<=right;x++){let v=0;for(let y=y0;y<y1;y++){const i=(y*img.width+x)*4;v+=(img.data[i]+img.data[i+1]+img.data[i+2])/3;}p.push(v/(y1-y0));}return p;};const spread=p=>{const low=p.slice(0,5).reduce((a,b)=>a+b)/5,high=p.slice(-5).reduce((a,b)=>a+b)/5,cross=f=>{const v=low+(high-low)*f;for(let i=1;i<p.length;i++)if(p[i]>=v&&p[i-1]<v)return i-1+(v-p[i-1])/(p[i]-p[i-1]);return NaN;};const width10to90=(cross(.9)-cross(.1))/Number(scale);let weight=0,moment=0;for(let i=1;i<p.length;i++){const w=Math.abs(p[i]-p[i-1]);weight+=w;moment+=w*Math.pow(left+i-.5-center,2);}return {width10to90,rms:Math.sqrt(moment/weight)/Number(scale),contrast:Math.abs(p.at(-1)-p[0])};};const stripe=img=>{let sum=0,sq=0,n=0;for(let y=y0;y<y1;y++)for(let x=Math.round(px+pw*.72);x<Math.round(px+pw*.9);x++){const i=(y*img.width+x)*4,v=(img.data[i]+img.data[i+1]+img.data[i+2])/3;sum+=v;sq+=v*v;n++;}return Math.sqrt(sq/n-(sum/n)**2);};detail.push({fraction,on:spread(profile(detailOn)),off:spread(profile(detailOff)),stripeRatio:stripe(detailOn)/stripe(detailOff)});}
  const top=band(2,8),middle=band(26,34),clear=band(-20,-10),row={kind,theme,scale,scroll,info,rect,top,middle,clear,detail,blurPixels:middle>2,progressive:top<middle*.65};
  assert.ok(row.blurPixels,'A gradient alone is not background blur: '+JSON.stringify(row));assert.equal(info.layers.length,4);rows.push(row);
 }
 // Text/buttons remain above the effect and receive input in the real document.
 if(kind!=='source'){await shell.locator('textarea').fill('Sharp input / 清晰输入');assert.equal(await shell.locator('textarea').inputValue(),'Sharp input / 清晰输入');}
 await page.close();
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(raw+'/'+engine+'-render-samples.json',JSON.stringify({environment:env,rows,errors},null,2));const candidates=rows.filter(r=>r.kind!=='source'),negative=rows.filter(r=>r.kind==='source');for(const r of candidates){assert.ok(r.progressive,'Candidate must pass the unchanged F3 gradient threshold');assert.ok(r.detail[2].on.width10to90>r.detail[0].on.width10to90+2,'Edge must actually spread with depth: '+JSON.stringify(r.detail));assert.ok(r.detail[0].stripeRatio>r.detail[2].stripeRatio+.15,'Stripe detail must progressively diffuse');assert.ok(r.detail.every(d=>d.on.contrast>2),'Not an opaque cover');}if(engine==='chromium99')assert.ok(negative.every(r=>!r.progressive),'Keep v26 failure as negative control');const progressive=candidates.every(r=>r.progressive),contained=rows.every(r=>r.clear<1);fs.writeFileSync(raw+'/'+engine+'-blur-render.json',JSON.stringify({environment:env,progressive,contained,rows,errors},null,2));console.log(JSON.stringify({engine,rows:rows.length,blurPixels:rows.every(r=>r.blurPixels),progressive,contained,scope:'Isolated browser, not real CEP',measurements:rows.map(({kind,theme,scale,scroll,top,middle,clear})=>({kind,theme,scale,scroll,top,middle,clear}))},null,2));if(!progressive||!contained)process.exitCode=2;
}finally{await browser.close();await server.close();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
