import {viewportRect} from '../geometry.js';
import {copy} from '../copy.js';
import {mountControls,disposeControls,isNumber} from '../controls.js';
import {captureFocus,restoreFocus} from './view-focus.js';
import {clone,uid,clamp} from './palette-model.js';
import {bezierCurve,curveBounds,curvePath,curveSegment,evaluateCurve,duplicateCurve,filterCurves,splitCurve,removeCurvePoint,moveCurvePoint,reverseCurve,curveToAE,validateCurveLibrary} from './curve-model.js';
import {curveStore,assetSettingsStore} from './curve-store.js';
import {useCurve,observeAssets,assetSummary} from './asset-runtime.js';
const cvEsc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cvButton=(action,label,extra='')=>`<button type="button" data-cv-action="${action}" ${extra}>${label}</button>`;
const cvNum=(label,key,value,min=-400,max=500,disabled=false)=>`<label class="pal-field"><span>${label}</span><input type="number" data-cv-field="${key}" value="${Number((value*100).toFixed(6))}" min="${min}" max="${max}" step="0.1" ${disabled?'disabled':''}><small class="cv-field-range">${Number(min.toFixed(3))}–${Number(max.toFixed(3))}%</small></label>`;
const cvSelected=(a,b)=>a===b?'selected':'';
export class CurveView{
 constructor(root,snapshot={}){this.root=root;this.store=curveStore();this.ui={page:'library',curveId:null,group:'all',query:'',groups:false,node:0,playhead:0,...snapshot};this.abort=new AbortController();this.notice='';this.noticeId='curve-notice-'+uid();this.drag=null;this.playing=false;this.frame=null;this.playEpoch=0;this.disposed=false;this.ui.playhead=0;const o={signal:this.abort.signal};for(const type of ['click','input','change','focusout','pointerdown','keydown'])root.addEventListener(type,e=>this[type](e),o);this.unsubscribe=this.store.subscribe(kind=>this.storeUpdate(kind));this.unobserve=observeAssets(()=>this.usage());this.render();}
 snapshot(){return {...this.ui,advancedOpen:this.root.querySelector('.cv-advanced')?.open??this.ui.advancedOpen,handlesOpen:this.root.querySelector('.cv-handles')?.hasAttribute('open')??this.ui.handlesOpen,exportOpen:this.root.querySelector('.cv-export')?.hasAttribute('open')??this.ui.exportOpen};}
 current(){return this.drag?.draft||this.store.data?.curves.find(c=>c.id===this.ui.curveId);}
 mutate(fn,options){try{this.store.change(fn,options);return true;}catch(e){this.message(e.message);return false;}}
 edit(fn,kind='curve-paint',undo=''){const id=this.current()?.id;if(!id)return;this.mutate(d=>{const c=d.curves.find(c=>c.id===id);if(c)fn(c);},{kind,undo});}
 message(text,error=false){text=copy(text);this.notice=text;const el=this.root.querySelector('.cv-notice');if(el){el.textContent=text;el.dataset.error=String(error);}}
 render(){this.ui=this.snapshot();const data=this.store.data;if(!data){disposeControls(this.root);this.root.innerHTML=`<div class="pal-empty"><p>${this.store.status==='loading'?copy("Loading curves…"):cvEsc(this.store.error)}</p>${this.store.status==='loading'?'':cvButton('reload',copy("Try again"))}</div>`;return;}
 if(!this.current()){this.stop(true);this.ui.curveId=data.curves[0]?.id||null;this.ui.node=0;}const c=this.current();if(c)this.ui.node=clamp(this.ui.node,0,c.nodes.length-1);
 const savedFocus=captureFocus(this.root),scroll=this.root.querySelector('.cv-catalog')?.scrollTop||0,detail=this.root.querySelector('.cv-detail')?.scrollTop||0;
 disposeControls(this.root);this.root.innerHTML=`<div class="cv-workspace" data-page="${this.ui.page}"><section class="cv-library" aria-label="${copy("Curve library")}"><div class="pal-library-top"><div class="pal-search-row"><input type="search" data-cv-field="search" placeholder="${copy("Search curves…")}" aria-label="${copy("Search curves")}" value="${cvEsc(this.ui.query)}">${cvButton('new',copy("+ New"),'class="primary-button"')}</div><div class="pal-filter-row"><select data-cv-field="group-filter" aria-label="${copy("Filter curves by group")}"><option value="all">${copy("All groups")}</option><option value="none" ${cvSelected(this.ui.group,'none')}>${copy("Ungrouped")}</option>${data.groups.map(g=>`<option value="${g.id}" ${cvSelected(g.id,this.ui.group)}>${cvEsc(g.name)}</option>`).join('')}</select>${cvButton('groups',copy("Groups"),`aria-expanded="${this.ui.groups}"`)}</div>${this.ui.groups?this.groups(data):''}</div><div class="cv-catalog">${this.catalog(data)}</div></section><section class="cv-detail" aria-label="${copy("Curve editor")}">${c?this.editor(c):`<div class="pal-empty">${copy("Create a curve to begin.")}</div>`}</section></div><div class="pal-library-footer"><span class="cv-save-status" role="status"></span><div>${cvButton('undo',copy("Undo"),this.store.undoEntry?'':'hidden')}${cvButton('retry',copy("Retry save"),'hidden')}${cvButton('reload',copy("Reload saved"),'hidden')}<details class="pal-file-menu"><summary>${copy("Library")}</summary><div>${cvButton('export-library',copy("Export library"))}${cvButton('import',copy("Import curves"))}<input data-cv-import type="file" accept=".json,application/json" hidden></div></details></div></div><p id="${this.noticeId}" class="cv-notice pal-notice" role="status">${cvEsc(this.notice)}</p>`;
 this.root.querySelector('.cv-catalog').scrollTop=scroll;this.root.querySelector('.cv-detail').scrollTop=detail;this.status();this.usage();this.drawPreview();
 mountControls(this.root);restoreFocus(this.root,savedFocus,this.ui.page==='library'?'[data-cv-field="search"]':'[data-cv-field="name"]');
 }
 groups(data){return `<div class="pal-group-manager"><div class="pal-new-group"><input data-cv-field="new-group" maxlength="80" placeholder="${copy("New group name")}" aria-label="${copy("New curve group")}">${cvButton('add-group',copy("Add"))}</div>${data.groups.map(g=>`<div class="pal-group-row"><input data-cv-group="${g.id}" value="${cvEsc(g.name)}" maxlength="80" aria-label="${cvEsc(copy('Rename {name}',{name:g.name}))}"><span>${data.curves.filter(c=>c.groupId===g.id).length}</span>${cvButton('delete-group','×',`data-id="${g.id}" aria-label="${cvEsc(copy('Delete {name} group; keep curves',{name:g.name}))}"`)}</div>`).join('')}</div>`;}
 catalog(data){const curves=filterCurves(data,this.ui);return `<div class="pal-count">${copy('{count} curves',{count:curves.length})}</div><div class="cv-card-grid">${curves.map(c=>`<button type="button" class="cv-card" data-cv-action="open" data-id="${c.id}" aria-pressed="${c.id===this.ui.curveId}" title="${cvEsc(c.name)}"><svg viewBox="0 0 140 76" aria-hidden="true"><path class="cv-mini-guide" d="M8 68H132M8 8V68"/><path data-cv-mini="${c.id}" d="${curvePath(c,{width:140,height:76,pad:8})}"/></svg><strong>${cvEsc(c.name)}</strong><span>${cvEsc(data.groups.find(g=>g.id===c.groupId)?.name||copy("Ungrouped"))}</span></button>`).join('')}</div>${curves.length?'':`<div class="pal-empty"><p>${copy("No matching curves.")}</p>${cvButton('clear',copy("Clear filters"))}</div>`}`;}
 editor(c){
  this.bounds=curveBounds(c);const i=this.ui.node,n=c.nodes[i],data=this.store.data,locked=i===0||i===c.nodes.length-1;
  const handles=['in','out'].filter(k=>k==='in'?i>0&&c.nodes[i-1].interpolation==='bezier':i<c.nodes.length-1&&n.interpolation==='bezier');
  if(!handles.includes(this.ui.selection))this.ui.selection='point';
  return `<div class="pal-detail-top">${cvButton('back',copy('‹ Library'),'class="pal-back"')}<input class="pal-title" data-cv-field="name" value="${cvEsc(c.name)}" maxlength="80" aria-label="${copy('Curve name')}"></div>
  <div class="cv-graph-wrap">${this.graph(c)}</div><div class="cv-graph-caption"><span>${copy('Time →')}</span><span>${copy('Value')} ↑ · ${c.nodes.length}</span>${cvButton('parameters',copy('Edit selected element'))}</div>
  <section class="cv-preview-settings"><div class="cv-demo"><div class="cv-demo-rail"></div><span class="cv-demo-dot"></span></div><div class="cv-playback">${cvButton('play',copy(this.playing?'Pause':'Replay'),'class="secondary-button"')}<input type="range" data-cv-field="playhead" min="0" max="1000" value="${this.ui.playhead*1000}" aria-label="${copy('Preview time')}"><output class="cv-preview-value"></output></div><label class="cv-duration"><span>${copy('Duration')}</span><input type="number" data-cv-field="duration" min="80" max="10000" step="10" value="${c.durationMs}" aria-label="${copy('Preview duration in milliseconds')}"><span>ms</span></label><p class="pal-muted">80–10000 ms · ${copy('Duration affects preview playback, not AE keyframes.')}</p></section>
  <section class="cv-parameter-area" aria-label="${copy('Node parameters')}"><header tabindex="-1"><strong>${copy('Selected element')}: ${copy(this.ui.selection==='in'?'Incoming handle':this.ui.selection==='out'?'Outgoing handle':'Node')} ${i+1}</strong>${cvButton('graph',copy('Back to curve'))}</header>
  <div class="cv-edit-tools"><select data-cv-field="node" aria-label="${copy('Selected curve point')}">${c.nodes.map((n,j)=>`<option value="${j}" ${cvSelected(j,i)}>${copy('Node')} ${j+1} · ${Math.round(n.t*100)}%</option>`).join('')}</select></div>
  <div class="cv-selection-controls" role="group" aria-label="${copy('Selected element')}">${['point',...handles].map(k=>cvButton('select-element',copy(k==='point'?'Node':k==='in'?'Incoming handle':'Outgoing handle'),`data-element="${k}" aria-pressed="${this.ui.selection===k}"`)).join('')}</div>
  ${locked?`<p class="cv-limit-note">${copy('Endpoints are fixed at (0%, 0%) and (100%, 100%).')}</p>`:this.ui.selection==='point'?`<fieldset data-cv-parameter="point" class="${(this.ui.selection||'point')==='point'?'is-selected':''}"><legend>${copy('Node parameters')}</legend><div class="cv-point-fields">${cvNum(copy('Time %'),'point-t',n.t,locked?0:c.nodes[i-1].t*100+.01,locked?100:c.nodes[i+1].t*100-.01,locked)}${cvNum(copy('Value %'),'point-v',n.v,-200,300,locked)}</div><p>${copy(locked?'Endpoints are fixed at (0%, 0%) and (100%, 100%).':'Time position within the curve; 0–100%.')} ${copy('Value relative to the unit interval; values may overshoot.')}</p></fieldset>`:''}

  <div class="cv-handles">${this.handleFields(c)}</div></section>

  <details class="cv-advanced" ${this.ui.advancedOpen?'open':''}><summary>${copy('Curve type, structure & UI motion')}</summary>
  <div class="cv-edit-tools"><select data-cv-field="interpolation" aria-label="${copy('Outgoing interpolation')}" ${i===c.nodes.length-1?'disabled':''}>${['bezier','linear','hold'].map(k=>`<option value="${k}" ${cvSelected(n.interpolation,k)}>${k==='bezier'?'Bézier':copy(k==='linear'?'Linear':'Hold')}</option>`).join('')}</select>${cvButton('flat',copy('Flat tangents'))}${cvButton('reverse',copy('Reverse'),c.nodes.some(n=>n.interpolation==='hold')?'disabled':'')}</div>
  <div class="cv-edit-tools">${cvButton('add-point',copy('+ Point'),i===c.nodes.length-1||c.nodes.length>=128?'disabled':'')}${cvButton('remove-point',copy('Remove'),locked?'disabled':'')}</div><div class="pal-detail-meta"><select data-cv-field="curve-group" aria-label="${copy('Curve group')}"><option value="none">${copy('Ungrouped')}</option>${data.groups.map(g=>`<option value="${g.id}" ${cvSelected(c.groupId,g.id)}>${cvEsc(g.name)}</option>`).join('')}</select>${cvButton('duplicate',copy('Duplicate'))}${cvButton('delete',copy('Delete'))}</div>
  <p class="cv-edit-hint">${copy('Drag a point or its handles. Arrow keys fine-tune; Shift moves faster. Split a segment to add a point without changing its shape.')}</p>
  <div class="cv-use"><div><span class="pal-muted">${copy('Plugin motion')}</span><strong data-cv-usage></strong></div>${cvButton('use',copy('Use for UI motion'),'class="primary-button"')}${cvButton('default-motion',copy('Default spring'))}<p class="pal-muted">${copy('Uses this curve with a duration up to 3000 ms.')} ${copy('This controls the reference UI motion only; it does not execute a curve in AE.')}</p><span data-runtime-status role="status"></span></div></details>`;
 }
 handleFields(c){const i=this.ui.node,n=c.nodes[i];return ['in','out'].map(kind=>{
  const incoming=kind==='in',exists=incoming?i>0:i<c.nodes.length-1,enabled=exists&&(incoming?c.nodes[i-1]:n).interpolation==='bezier',point=exists?(incoming?curveSegment(c.nodes[i-1],n)[2]:curveSegment(n,c.nodes[i+1])[1]):null;
  if(!exists)return '';
  if(!enabled)return `<p class="cv-limit-note">${copy(incoming?'Incoming handle':'Outgoing handle')} · ${copy('Handles apply only to Bézier segments. Choose Bézier to edit.')} ${cvButton('structure',copy('Curve type'))}</p>`;
  if(this.ui.selection!==kind)return '';
  return `<fieldset data-cv-parameter="${kind}" class="${this.ui.selection===kind?'is-selected':''}"><legend>${copy(incoming?'Incoming handle':'Outgoing handle')}</legend>${point?`<div class="cv-handle-fields">${cvNum(copy('Time %'),kind+'-t',point[0],(incoming?c.nodes[i-1].t:n.t)*100,(incoming?n.t:c.nodes[i+1].t)*100,!enabled)}${cvNum(copy('Value %'),kind+'-v',point[1],-400,500,!enabled)}</div>`:''}<p>${copy(!exists?incoming?'No incoming segment at the first node.':'No outgoing segment at the last node.':enabled?'Time is bounded by the adjacent nodes. Value range: −400–500%.':'Handles apply only to Bézier segments. Choose Bézier to edit.')}</p></fieldset>`;
 }).join('');}
 coords(t,v){const b=this.dragBounds||this.bounds;return [24+t*352,24+(b.max-v)/(b.max-b.min)*200];}
 graph(c){const [x0,y0]=this.coords(0,0),[x1,y1]=this.coords(1,1),i=this.ui.node,n=c.nodes[i];let handles='';for(const kind of ['in','out']){const p=kind==='in'&&i?curveSegment(c.nodes[i-1],n)[2]:kind==='out'&&i<c.nodes.length-1?curveSegment(n,c.nodes[i+1])[1]:null;if(p&&(kind==='in'?c.nodes[i-1]:n).interpolation==='bezier'){const [x,y]=this.coords(...p),[nx,ny]=this.coords(n.t,n.v);handles+=`<line data-cv-line="${kind}" x1="${nx}" y1="${ny}" x2="${x}" y2="${y}"/><circle data-cv-handle="${kind}" data-cv-node="${i}" cx="${x}" cy="${y}" r="5" class="${this.ui.selection===kind?'is-selected':''}" tabindex="0" role="slider" aria-label="${copy('{kind} handle for point {index}',{kind:copy(kind==='in'?'Incoming':'Outgoing'),index:i+1})}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${p[0]*100}" aria-valuetext="${this.pointValueText(p)}"/>`;}}
 return `<svg class="cv-graph" viewBox="0 0 400 248" role="group" aria-label="${copy("Editable time and value curve")}"><path class="cv-grid" d="M24 24V224H376M24 ${y0}H376M24 ${y1}H376M200 24V224"/><text x="7" y="${y0+4}">0</text><text x="2" y="${y1+4}">1</text><path class="cv-curve-path" d="${curvePath(c,{width:400,height:248,pad:24,bounds:this.dragBounds||this.bounds})}"/><g class="cv-handles-drawing">${handles}</g><g class="cv-nodes">${c.nodes.map((n,j)=>{const [x,y]=this.coords(n.t,n.v);return `<circle data-cv-handle="point" data-cv-node="${j}" cx="${x}" cy="${y}" r="${j===i?5:3.5}" class="${j===i?'is-selected':''}" tabindex="0" role="slider" aria-label="${copy('Point {index}',{index:j+1})}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${n.t*100}" aria-valuetext="${this.pointValueText([n.t,n.v],j===0||j===c.nodes.length-1)}"/>`;}).join('')}</g><line class="cv-playhead" x1="24" x2="24" y1="24" y2="224"/><circle class="cv-graph-dot" cx="24" cy="${y0}" r="4"/></svg>`;}
 paint(){const c=this.current();if(!c||!this.root.querySelector('.cv-graph'))return;const graph=this.root.querySelector('.cv-graph');graph.querySelector('.cv-curve-path').setAttribute('d',curvePath(c,{width:400,height:248,pad:24,bounds:this.dragBounds||this.bounds}));const i=this.ui.node,n=c.nodes[i];graph.querySelectorAll('[data-cv-handle]').forEach(el=>{const j=Number(el.dataset.cvNode),node=c.nodes[j];if(!node)return;const kind=el.dataset.cvHandle,p=kind==='point'?[node.t,node.v]:kind==='in'&&j?curveSegment(c.nodes[j-1],node)[2]:kind==='out'&&j<c.nodes.length-1?curveSegment(node,c.nodes[j+1])[1]:null;if(!p)return;const [x,y]=this.coords(...p);el.setAttribute('cx',x);el.setAttribute('cy',y);el.setAttribute('aria-valuenow',p[0]*100);el.setAttribute('aria-valuetext',this.pointValueText(p,kind==='point'&&(j===0||j===c.nodes.length-1)));const line=graph.querySelector(`[data-cv-line="${kind}"]`);if(line){const [nx,ny]=this.coords(node.t,node.v);line.setAttribute('x1',nx);line.setAttribute('y1',ny);line.setAttribute('x2',x);line.setAttribute('y2',y);}});
 for(const [key,val]of [['point-t',n.t],['point-v',n.v],...['in','out'].flatMap(k=>{const p=k==='in'&&i?curveSegment(c.nodes[i-1],n)[2]:k==='out'&&i<c.nodes.length-1?curveSegment(n,c.nodes[i+1])[1]:null;return p?[[k+'-t',p[0]],[k+'-v',p[1]]]:[];})]){const el=this.root.querySelector(`[data-cv-field="${key}"]`);if(el&&el!==document.activeElement)el.value=Number((val*100).toFixed(6));}
 this.root.querySelector(`[data-cv-mini="${c.id}"]`)?.setAttribute('d',curvePath(c,{width:140,height:76,pad:8}));this.drawPreview();this.status();}
 pointValueText(p,locked=false){return `${copy('Time {time}%, value {value}%',{time:+(p[0]*100).toFixed(2),value:+(p[1]*100).toFixed(2)})}${locked?copy("; fixed endpoint"):copy("; Left/Right adjust time, Up/Down adjust value")}`;}
 status(){const el=this.root.querySelector('.cv-save-status');if(!el)return;el.textContent=this.root.querySelector('[aria-invalid="true"]')?copy("Check input"):this.drag?copy("Editing curve…"):{loading:copy("Loading…"),saved:copy("Saved"),saving:copy("Saving…"),unsaved:copy("Unsaved changes"),error:copy("Save unavailable"),conflict:copy("Save conflict")}[this.store.status];this.root.querySelector('[data-cv-action="undo"]').hidden=!this.store.undoEntry;this.root.querySelector('[data-cv-action="retry"]').hidden=this.store.status!=='error';this.root.querySelector('[data-cv-action="reload"]').hidden=this.store.status!=='conflict';if(this.store.error)this.message(this.store.error);}
 usage(){const el=this.root.querySelector('[data-cv-usage]');if(el)el.textContent=assetSummary().motion;}
 drawPreview(){const c=this.current(),graph=this.root.querySelector('.cv-graph');if(!c||!graph)return;const t=this.ui.playhead,v=evaluateCurve(c,t),[x,y]=this.coords(t,v),dot=graph.querySelector('.cv-graph-dot');dot.setAttribute('cx',x);dot.setAttribute('cy',y);const line=graph.querySelector('.cv-playhead');line.setAttribute('x1',x);line.setAttribute('x2',x);const b=this.dragBounds||this.bounds,map=value=>clamp((value-b.min)/(b.max-b.min))*100;this.root.querySelector('.cv-demo-dot').style.left=map(v)+'%';const rail=this.root.querySelector('.cv-demo-rail');rail.style.left=map(0)+'%';rail.style.width=map(1)-map(0)+'%';this.root.querySelector('.cv-preview-value').textContent=Math.round(v*100)+'%';const slider=this.root.querySelector('[data-cv-field="playhead"]');if(slider!==document.activeElement)slider.value=t*1000;}
 play(){
  if(this.disposed)return;if(this.playing){this.stop();return;}const curveId=this.current()?.id;if(!curveId)return;
  const epoch=++this.playEpoch;this.playing=true;if(this.ui.playhead>=1)this.ui.playhead=0;this.last=performance.now();
  const button=this.root.querySelector('[data-cv-action="play"]');if(button)button.textContent=copy('Pause');
  const tick=now=>{
   // A cancelled callback must not clear a newer frame or advance another curve.
   if(this.disposed||epoch!==this.playEpoch||!this.playing)return;
   this.frame=null;const c=this.current();if(c?.id!==curveId){this.stop(true);return;}
   this.ui.playhead=clamp(this.ui.playhead+(now-this.last)/c.durationMs);this.last=now;this.drawPreview();
   if(this.ui.playhead>=1||document.hidden)this.stop();else this.frame=requestAnimationFrame(tick);
  };
  if(typeof requestAnimationFrame==='function')this.frame=requestAnimationFrame(tick);
 }
 stop(reset=false){this.playEpoch++;this.playing=false;if(this.frame!==null)cancelAnimationFrame(this.frame);this.frame=null;if(reset)this.ui.playhead=0;const b=this.root.querySelector('[data-cv-action="play"]');if(b)b.textContent=copy('Replay');}
 click(e){const button=e.target.closest('[data-cv-action]');if(!button||button.disabled)return;const action=button.dataset.cvAction,c=this.current();
 if(action==='select-element'){this.ui.selection=button.dataset.element;this.render();this.root.querySelector('[data-element="'+this.ui.selection+'"]')?.focus({preventScroll:true});return;}if(action==='structure'){const details=this.root.querySelector('.cv-advanced');details.open=true;details.querySelector('[data-cv-field=interpolation]')._coreSelectComponent?.trigger.focus();return;}if(action==='parameters'){const area=this.root.querySelector('.cv-parameter-area');area.scrollIntoView({block:'start'});area.querySelector('header').focus({preventScroll:true});return;}if(action==='graph'){const handle=this.root.querySelector(`[data-cv-handle="${this.ui.selection||'point'}"][data-cv-node="${this.ui.node}"]`);handle?.scrollIntoView({block:'center'});handle?.focus({preventScroll:true});return;}if(action==='open'){this.stop();this.ui.curveId=button.dataset.id;this.ui.node=0;this.ui.selection='point';this.ui.page='curve';this.ui.playhead=0;this.render();this.root.querySelector('[data-cv-field="name"]')?.focus({preventScroll:true});return;}if(action==='back'){this.ui.page='library';this.stop();this.render();(this.root.querySelector(`[data-cv-action="open"][data-id="${c?.id}"]`)||this.root.querySelector('[data-cv-field="search"]'))?.focus({preventScroll:true});return;}if(action==='groups'){this.ui.groups=!this.ui.groups;this.render();return;}if(action==='clear'){this.ui.query='';this.ui.group='all';this.render();return;}
 if(action==='new'){this.stop(true);const n=bezierCurve(copy("Untitled curve"));n.groupId=this.store.data.groups.some(g=>g.id===this.ui.group)?this.ui.group:null;this.ui.curveId=n.id;this.ui.page='curve';this.ui.node=0;this.mutate(d=>d.curves.unshift(n));this.root.querySelector('[data-cv-field="name"]')?.select();return;}
 if(action==='duplicate'&&c){this.stop(true);const n=duplicateCurve(c);this.ui.curveId=n.id;this.mutate(d=>d.curves.splice(d.curves.findIndex(x=>x.id===c.id)+1,0,n));return;}if(action==='delete'&&c){this.stop(true);this.mutate(d=>d.curves=d.curves.filter(x=>x.id!==c.id),{undo:'Delete curve'});return;}
 if(action==='add-group'){const input=this.root.querySelector('[data-cv-field="new-group"]'),name=input.value.trim();if(!name){input.focus();return;}this.mutate(d=>d.groups.push({id:uid(),name}));return;}if(action==='delete-group'){this.ui.group='all';this.mutate(d=>{d.groups=d.groups.filter(g=>g.id!==button.dataset.id);d.curves.forEach(c=>{if(c.groupId===button.dataset.id)c.groupId=null;});},{undo:'Delete group'});return;}
 if(action==='play'){this.play();return;}if(action==='add-point'){this.edit(c=>{const n=splitCurve(c,this.ui.node);this.ui.node=c.nodes.indexOf(n);},'render','Split segment');return;}if(action==='remove-point'){this.edit(c=>{removeCurvePoint(c,this.ui.node);this.ui.node--;},'render','Remove point');return;}if(action==='reverse'){this.edit(reverseCurve,'render','Reverse curve');return;}
 if(action==='flat'){this.edit(c=>{const i=this.ui.node,n=c.nodes[i];if(i){n.in=[n.t-(n.t-c.nodes[i-1].t)/3,n.v];c.nodes[i-1].interpolation='bezier';}if(i<c.nodes.length-1){n.out=[n.t+(c.nodes[i+1].t-n.t)/3,n.v];n.interpolation='bezier';}},'render','Flatten tangents');return;}
 if(action==='undo'){this.store.undo();return;}if(action==='retry'){this.store.flush();return;}if(action==='reload'){this.store.reload();return;}
 if(action==='use'||action==='default-motion'){try{useCurve(action==='use'?c.id:null,action==='use'?c.durationMs:400);this.message(action==='use'?'This curve now drives plugin motion.':'Default spring restored.');}catch(error){this.message(error.message);}return;}
 if(action==='export-library'){this.download(this.store.data,'lomond-curves.json');return;}if(action==='export-curve'){this.download({schema:'lomond.curve-export/1',curve:clone(c)},'lomond-curve.json');return;}if(action==='export-ae'){try{const plan=curveToAE(c,{duration:c.durationMs/1000,startValue:this.ui.aeStart??0,endValue:this.ui.aeEnd??100});this.download({curve:clone(c),...plan},'lomond-ae-curve.json');this.message(plan.mode==='mixed-sampled'?'Exported keyframes; very short handles use sampled segments.':'Exported temporal keyframe data.');}catch(error){this.message(error.message);}return;}if(action==='import'){this.root.querySelector('[data-cv-import]').click();}
 }
 input(e){const el=e.target,key=el.dataset.cvField;if(key==='search'){this.ui.query=el.value;this.render();return;}if(key==='playhead'){this.stop();this.ui.playhead=Number(el.value)/1000;this.drawPreview();return;}if(isNumber(el))this.field(el,false);}
 change(e){const el=e.target;if(el.hasAttribute('data-cv-import')){this.importFile(el.files[0]);return;}if(el.dataset.cvGroup){this.mutate(d=>d.groups.find(g=>g.id===el.dataset.cvGroup).name=el.value.trim());return;}if(el.dataset.cvField)this.field(el,true);}
 focusout(e){if(e.target.getAttribute('aria-invalid')==='true')this.field(e.target,true);}
 numericValue(key){const c=this.current(),n=c?.nodes[this.ui.node];if(key==='duration')return c?.durationMs;if(key==='ae-start'||key==='ae-end')return this.ui[key==='ae-start'?'aeStart':'aeEnd']??(key==='ae-start'?0:100);if(key==='point-t')return n.t*100;if(key==='point-v')return n.v*100;if(/^(in|out)-(t|v)$/.test(key)){const [kind,axis]=key.split('-'),p=kind==='in'?curveSegment(c.nodes[this.ui.node-1],n)[2]:curveSegment(n,c.nodes[this.ui.node+1])[1];return p[axis==='t'?0:1]*100;}}
 validateNumber(el,commit){const value=el.value,n=Number(value),min=el.getAttribute?.('min'),max=el.getAttribute?.('max'),invalid=value===''||!Number.isFinite(n)||el.validity?.valid===false||(min!=null&&n<Number(min))||(max!=null&&n>Number(max));if(!invalid){el.removeAttribute?.('aria-invalid');if(this.fieldErrorKey===el.dataset.cvField){this.fieldErrorKey=null;this.message('');}this.status();return true;}this.fieldErrorKey=el.dataset.cvField;el.setAttribute?.('aria-invalid','true');el.setAttribute?.('aria-describedby',this.noticeId);const rule=min!=null&&max!=null?copy('Enter a value from {min} to {max}, using the field step.',{min,max}):copy("Enter a valid number.");if(commit){el.value=String(this.numericValue(el.dataset.cvField));el.removeAttribute?.('aria-invalid');this.message(rule+copy(" Previous value restored."),true);}else this.message(rule+copy(" This edit has not been applied."),true);this.status();return false;}
 field(el,commit){const key=el.dataset.cvField,value=el.value,number=Number(value),c=this.current();if(isNumber(el)&&!this.validateNumber(el,commit))return;if(key==='search'||key==='new-group'||key==='playhead')return;if(key==='group-filter'){this.ui.group=value;this.render();return;}if(key==='node'){this.ui.node=number;this.ui.selection='point';this.render();return;}if(key==='ae-start'||key==='ae-end'){this.ui[key==='ae-start'?'aeStart':'aeEnd']=number;return;}if(!c)return;
 if(key==='name'){this.edit(c=>c.name=value.trim(),'render');return;}if(key==='curve-group'){this.edit(c=>c.groupId=value==='none'?null:value,'render');return;}if(key==='duration'){this.edit(c=>c.durationMs=number);return;}if(key==='interpolation'){this.edit(c=>c.nodes[this.ui.node].interpolation=value,'render','Change interpolation');return;}
 this.edit(c=>{const i=this.ui.node,n=c.nodes[i];if(key==='point-t'||key==='point-v')moveCurvePoint(c,i,key==='point-t'?number/100:n.t,key==='point-v'?number/100:n.v);else if(/^(in|out)-(t|v)$/.test(key)){const [kind,axis]=key.split('-'),p=kind==='in'?curveSegment(c.nodes[i-1],n)[2]:curveSegment(n,c.nodes[i+1])[1];p[axis==='t'?0:1]=axis==='t'?clamp(number/100,kind==='in'?c.nodes[i-1].t:n.t,kind==='in'?n.t:c.nodes[i+1].t):number/100;n[kind]=p;}},'curve-paint');if(commit)this.render();}
 storeUpdate(kind){
  if(this.drag){const c=this.store.data?.curves.find(c=>c.id===this.drag.base.id);if(!c||JSON.stringify(c)!==this.drag.signature){this.endDrag(false);this.message(copy("This curve changed elsewhere. Your drag was cancelled."),true);}else this.status();return;}
  if(kind==='status')this.status();else if(kind==='curve-paint')this.paint();else this.render();
 }
 flushDrag(){const d=this.drag;if(!d||!d.pending)return;const {t,v}=d.pending;d.pending=null;const c=d.draft,n=c.nodes[d.index];if(d.kind==='point')moveCurvePoint(c,d.index,t,v);else n[d.kind]=[clamp(t,d.kind==='in'?c.nodes[d.index-1].t:n.t,d.kind==='in'?n.t:c.nodes[d.index+1].t),clamp(v,-4,5)];this.paint();}
 endDrag(commit,render=true){const d=this.drag;if(!d)return;if(d.frame!==null)cancelAnimationFrame(d.frame);if(commit)this.flushDrag();d.events.abort();this.drag=null;if(d.target.hasPointerCapture?.(d.pointerId))d.target.releasePointerCapture(d.pointerId);this.dragBounds=null;
  if(commit&&JSON.stringify(d.draft)!==d.signature)this.mutate(data=>{const i=data.curves.findIndex(c=>c.id===d.base.id);if(i<0||JSON.stringify(data.curves[i])!==d.signature)throw new Error(copy("This curve changed elsewhere. Reopen it before editing."));data.curves[i]=d.draft;},{kind:'curve-paint',undo:'Move curve point'});
  if(render){this.render();this.root.querySelector(`[data-cv-handle="${d.kind}"][data-cv-node="${d.index}"]`)?.focus({preventScroll:true});}
 }
 pointerdown(e){
  const point=e.target.closest('[data-cv-handle]');if(!point||e.button!==0)return;e.preventDefault();this.endDrag(false);this.stop();const index=Number(point.dataset.cvNode),kind=point.dataset.cvHandle;this.ui.node=index;this.ui.selection=kind;this.render();this.dragBounds={...this.bounds};
  const target=this.root.querySelector(`[data-cv-handle="${kind}"][data-cv-node="${index}"]`),rect=viewportRect(this.root.querySelector('.cv-graph')),base=clone(this.current()),events=new AbortController();
  this.drag={target,pointerId:e.pointerId,base,draft:clone(base),signature:JSON.stringify(base),index,kind,events,frame:null,pending:null};target.focus({preventScroll:true});target.setPointerCapture?.(e.pointerId);this.status();
  const move=ev=>{const d=this.drag;if(!d||ev.pointerId!==e.pointerId||!rect.width||!rect.height)return;const x=(ev.clientX-rect.left)/rect.width*400,y=(ev.clientY-rect.top)/rect.height*248;d.pending={t:(x-24)/352,v:this.dragBounds.max-(y-24)/200*(this.dragBounds.max-this.dragBounds.min)};if(d.frame===null)d.frame=requestAnimationFrame(()=>{if(this.drag!==d)return;d.frame=null;this.flushDrag();});};
  const end=ev=>{if(ev.pointerId===e.pointerId){if(ev.type==='pointerup')move(ev);this.endDrag(ev.type==='pointerup');}};target.addEventListener('pointermove',move,{signal:events.signal});for(const type of ['pointerup','pointercancel','lostpointercapture'])target.addEventListener(type,end,{signal:events.signal});
 }
 keydown(e){if(e.target.dataset.cvField==='new-group'&&e.key==='Enter'){e.preventDefault();this.root.querySelector('[data-cv-action="add-group"]').click();return;}const el=e.target.closest('[data-cv-handle]');if(!el||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter'].includes(e.key))return;e.preventDefault();const i=Number(el.dataset.cvNode),kind=el.dataset.cvHandle;this.ui.node=i;this.ui.selection=kind;this.render();this.root.querySelector(`[data-cv-handle="${kind}"][data-cv-node="${i}"]`)?.focus({preventScroll:true});if(e.key==='Enter')return;const dx=(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)*(e.shiftKey?.05:.005),dy=(e.key==='ArrowUp'?1:e.key==='ArrowDown'?-1:0)*(e.shiftKey?.05:.005);this.edit(c=>{const n=c.nodes[i];if(kind==='point')moveCurvePoint(c,i,n.t+dx,n.v+dy);else{const p=kind==='in'?curveSegment(c.nodes[i-1],n)[2]:curveSegment(n,c.nodes[i+1])[1];n[kind]=[clamp(p[0]+dx,kind==='in'?c.nodes[i-1].t:n.t,kind==='in'?n.t:c.nodes[i+1].t),clamp(p[1]+dy,-4,5)];}});}
 download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async importFile(file){if(!file)return;try{if(file.size>2_000_000)throw new Error('Choose a file smaller than 2 MB.');const parsed=JSON.parse(await file.text()),data=parsed.schema==='lomond.curve-export/1'?{schemaVersion:1,groups:[],curves:[{...parsed.curve,groupId:null}]}:parsed;validateCurveLibrary(data);const imported=this.mutate(d=>{const groups=new Map();for(const g of data.groups){let existing=d.groups.find(x=>x.name.toLowerCase()===g.name.toLowerCase());if(!existing){existing={id:uid(),name:g.name};d.groups.push(existing);}groups.set(g.id,existing.id);}for(const c of data.curves){const copy=duplicateCurve(c);copy.name=c.name;copy.groupId=c.groupId?groups.get(c.groupId):null;d.curves.push(copy);}},{undo:copy("Import curves")});if(imported)this.message(copy("Curves imported."));}catch(error){this.message(error.message);}}
 destroy(){this.disposed=true;disposeControls(this.root);this.endDrag(false,false);this.stop();this.abort.abort();this.unsubscribe();this.unobserve();}
}
