import {icon} from './icons.js';
import {copy} from './copy.js';
import '../../js/vela/velaPresentationModel.js';
import fixtures from './vela-fixtures.json';
import {referencePhase} from './vela-projection.js';
import {esc,t,bilingual,preserveReading} from './shared.js';
import {mountControls,disposeControls} from './controls.js';
export const stateNames={review:['Awaiting approval','待批准'],executing:['Executing','执行中'],partial:['Partially completed','部分完成'],rejected:['Rejected','已拒绝'],cancelled:['Cancelled','已取消'],failed:['Failed','失败'],completed:['Completed','完成']};
const name=cap=>cap==='set-opacity-v1'?bilingual('Set layer opacity','调整图层不透明度'):cap==='set-layer-name-v1'?bilingual('Rename layer','重命名图层'):cap;
const value=(v,cap)=>v===null||v===undefined?'—':String(v)+(cap==='set-opacity-v1'?'%':'');
export class ReferenceVela {
 constructor(root,{state='review',draft='',messages=[]}={}){
  Object.assign(this,{root,state,draft,messages});this.abort=new AbortController();this.render();const o={signal:this.abort.signal};
  root.addEventListener('change',e=>{if(e.target.matches('[data-vela-state]')){this.state=e.target.value;this.renderProjection();}},o);
  root.addEventListener('input',e=>{if(e.target.matches('textarea')){this.draft=e.target.value;this.layoutComposer();}},o);
  root.addEventListener('compositionstart',()=>this.composing=true,o);root.addEventListener('compositionend',()=>this.composing=false,o);
  root.addEventListener('keydown',e=>{if(e.target.matches('textarea')&&e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&!e.isComposing&&!this.composing&&e.keyCode!==229){e.preventDefault();this.send();}},o);
  root.addEventListener('submit',e=>{e.preventDefault();this.send();},o);
  root.addEventListener('click',e=>{if(e.target.closest('[data-vela-long]'))this.append(bilingual('Additional fixture evidence. ','新增模拟证据。').repeat(35),false);if(e.target.closest('[data-isolated-command]')||e.target.closest('[data-vela-send]')&&this.state==='executing'){e.preventDefault();this.commandStatus(bilingual('Command isolated. Select a captured state to inspect its facts.','命令已隔离。请用状态选择器查看捕获的事实。'));return;}},o);
  this.resize=new ResizeObserver(()=>this.layoutComposer());this.resize.observe(root.querySelector('.composer'));this.resize.observe(root.querySelector('.vela-shell'));
 }
 render(){
  disposeControls(this.root);
  // v26 Vela roles; no LifecyclePlayer. Facts come exclusively from source ports.
  this.root.innerHTML=`<div class="ref-vela-tools"><label>${esc(t('reference.state'))}<select data-vela-state>${Object.entries(stateNames).map(([key,names])=>`<option value="${key}" ${key===this.state?'selected':''}>${esc(bilingual(...names))}</option>`).join('')}</select></label><button data-vela-long>${esc(bilingual('Append long evidence','追加长证据'))}</button></div>
  <section class="vela-shell" aria-label="${esc(bilingual('Vela conversation','Vela 会话'))}"><div class="vela-content-clip"><header class="vela-header"><div class="vela-title">${icon('vela')}<h3>Vela</h3></div><span class="composition-name">${esc(bilingual('Isolated Runtime fixture','隔离 Runtime 模拟'))}</span><button class="icon-button" type="button" data-isolated-command="new" aria-label="${esc(t('vela.conversationNew'))}" title="${esc(t('reference.fixture'))}">${icon('plus')}</button></header>
  <div class="messages ref-transcript" tabindex="0" aria-label="${esc(bilingual('Conversation messages','会话消息'))}"><div class="message user"><p>把当前图层的不透明度改成 60%，然后把它重命名为 Vela Stream Test</p></div><div class="message turn-assistant"><div class="message-label"><span class="sender">Vela</span><span>·</span><span>${esc(bilingual('Captured state','捕获状态'))}</span></div><p class="reply-line">${esc(bilingual('Only the current step is reviewed. Completed work remains a fact after rejection or failure.','批准范围仅限当前步；后续拒绝或失败不会撤销已完成事实。'))}</p><div class="ref-projection phase-detail"></div></div>${this.messages.map(m=>this.messageHTML(m)).join('')}</div></div>
  <div class="composer-haze" aria-hidden="true"><span></span><span></span><span></span><span></span></div><form class="composer" aria-label="${esc(bilingual('Draft · Provider disabled','起草 · Provider 未启用'))}"><div class="composer-box"><textarea id="ref-draft" rows="1" aria-label="${esc(bilingual('Message Vela','给 Vela 的消息'))}" placeholder="${esc(bilingual('Ask Vela or describe an edit…','向 Vela 提问或描述修改……'))}">${esc(this.draft)}</textarea></div><div class="composer-toolbar"><div class="settings-slot"><button class="icon-button settings-button" type="button" data-vela-appearance aria-label="${esc(t('settings.navigation.appearance'))}">${icon('settings')}</button></div><div class="composer-status" role="status"><span class="status-dot" aria-hidden="true"></span><span class="status-label"></span></div><div class="composer-actions"><button class="secondary-button review-cancel" type="button" data-isolated-command="reject">${esc(bilingual('Reject','拒绝'))}</button><button class="primary-button" type="button" data-isolated-command="approve">${esc(bilingual('Approve','批准'))}</button><button class="send-button" type="submit" data-vela-send aria-label="${esc(t('vela.surfaceSend'))}">${icon('send')}</button></div></div><p class="ref-composer-hint">${esc(bilingual('Enter: new line · Ctrl/Cmd+Enter: fixture send','Enter 换行 · Ctrl/Cmd+Enter 模拟发送'))}</p><p role="status" data-command-status></p></form></section>`;
  mountControls(this.root);this.renderProjection();this.layoutComposer();this.root.querySelector('.messages').scrollTop=this.root.querySelector('.messages').scrollHeight;
 }
 reviewHTML(r){return `<div class="proposal" data-review-id="${esc(r.reviewId)}"><div class="proposal-header">${esc(name(r.capabilityId))} <span class="panel-status">/ ${esc(bilingual('Review','审阅'))}</span></div><div class="change-row"><span title="${esc(r.target.layerId)}">${copy('Selected layer')}</span><span><span class="old">${esc(value(r.beforeValue,r.capabilityId))}</span> → <span class="new">${esc(value(r.proposedValue,r.capabilityId))}</span></span></div><p class="proposal-note">${esc(bilingual('Current step','当前步'))} ${r.stepNumber} / ${r.stepCount} · ${esc(bilingual('Before → proposed','原值 → 提议值'))}</p><details class="ref-review-identity"><summary>${esc(bilingual('Review identity and target','Review 身份与目标'))}</summary><dl><dt>${copy('Review ID')}</dt><dd>${esc(r.reviewId)}</dd><dt>${esc(bilingual('Revision / scope','修订 / 范围'))}</dt><dd>${r.revision} / ${esc(r.approvalScope)}</dd><dt>${esc(bilingual('Composition / layer','合成 / 图层'))}</dt><dd>${esc(r.target.compId)} / ${esc(r.target.layerId)}</dd></dl></details></div>`;}
 renderProjection(){
  const f=fixtures[this.state],trajectory=f.trajectory.active||f.trajectory.terminal,logical=f.driver.logicalPlan,phase=referencePhase(f),projection=self.VelaPresentationModel.projectSurfaceState(f.provider,f.confirmation,this.draft,true,'ready'),transcript=this.root.querySelector('.messages');
  this.root.querySelector('.vela-shell').dataset.ui=phase;this.root.querySelector('.reply-line').textContent=copy(phase==='review'?'I can apply this step after your approval.':'Captured execution facts are shown below.');this.root.querySelector('textarea').placeholder=phase==='review'?copy('Review the proposed change above'):bilingual('Ask Vela or describe an edit…','向 Vela 提问或描述修改……');this.root.querySelector('.status-label').textContent=bilingual(...stateNames[phase]);
  const send=this.root.querySelector('[data-vela-send]');send.innerHTML=icon(phase==='executing'?'stop':'send');send.setAttribute('aria-label',t(phase==='executing'?'vela.surfaceCancel':'vela.surfaceSend'));
  for(const el of this.root.querySelectorAll('[data-isolated-command=approve],[data-isolated-command=reject]'))el.hidden=phase!=='review';
  this.root.querySelector('[data-isolated-command=approve]').disabled=!f.confirmation.canApprove;
  preserveReading(transcript,()=>{const attempts=(trajectory?.attempts||[]).filter(a=>a.execution?.executionAttempted||a.execution?.hostCommitted===true||a.completion?.outcome!=='active');
   this.root.querySelector('.ref-projection').innerHTML=`<header class="terminal-label"><span class="ref-state" data-phase="${phase}" data-tone="${projection.tone}">${esc(bilingual(...stateNames[phase]))}</span></header><p class="detail-line">${esc(bilingual('Current step','当前步'))}: ${(logical?.currentStepIndex??0)+1} / ${logical?.stepCount??1} · ${esc(bilingual('Completed','已完成'))}: ${logical?.completedStepCount??0}</p>${f.reviews.map(r=>this.reviewHTML(r)).join('')}${attempts.length?`<ol class="steps ref-execution-facts">${attempts.map((a,i)=>`<li class="${a.completion?.outcome==='completed'?'done':'pending'}"><span class="step-icon">${a.completion?.outcome==='completed'?icon('check'):a.completion?.outcome==='active'&&phase==='executing'?icon('loader','rotation'):String(i+1)}</span><div><strong>${esc(name(a.capabilityId))}</strong><p class="detail-line">${esc(bilingual('Completion','完成情况'))}: ${esc(a.completion?.outcome??'unknown')} · ${esc(bilingual('Committed','已提交变更'))}: ${esc(String(a.execution?.hostCommitted??'unknown'))}</p><p class="detail-line">Verify: ${esc(a.verification?.disposition??'unknown')} · ${esc(a.verification?.scope??'unknown')}</p><p class="detail-line">${esc(bilingual('Expected / observed','期望 / 观察值'))}: ${esc(JSON.stringify(a.verification?.expected?.data??null))} / ${esc(JSON.stringify(a.verification?.actual?.data??null))}</p></div></li>`).join('')}</ol>`:''}${phase==='partial'||phase==='failed'?`<p class="completion-meta">${esc(bilingual('Committed changes remain. No automatic rollback.','已提交变更保留，不会自动回滚。'))}</p>`:''}<details class="ref-runtime-detail"><summary>${esc(bilingual('Runtime projection and provenance','Runtime 投影与证据来源'))}</summary><pre>${esc(JSON.stringify({surfaceProjection:projection,provider:f.provider,confirmation:f.confirmation,driver:f.driver,trajectory},null,2))}</pre></details>`;
  });this.layoutComposer();
 }
 layoutComposer(){if(!this.root.isConnected)return;this.root.querySelector('[data-vela-send]').hidden=referencePhase(fixtures[this.state])==='review'&&!this.draft.trim();const shell=this.root.querySelector('.vela-shell'),input=shell.querySelector('textarea'),messages=shell.querySelector('.messages');preserveReading(messages,()=>{input.style.height='24px';input.style.height=Math.min(72,Math.max(24,input.scrollHeight))+'px';const height=shell.querySelector('.composer').offsetHeight,clear=shell.clientHeight-shell.querySelector('.vela-header').offsetHeight-height;shell.style.setProperty('--composer-height',height+'px');shell.style.setProperty('--composer-fade',Math.min(48,Math.max(16,clear-72))+'px');});}
 messageHTML(m){return `<div class="message ${m.user?'user':''}"><p>${esc(m.text??m)}</p></div>`;}
 append(text,user=true){const transcript=this.root.querySelector('.messages'),message={text,user};this.messages.push(message);preserveReading(transcript,()=>transcript.insertAdjacentHTML('beforeend',this.messageHTML(message)));}
 commandStatus(text){this.root.querySelector('[data-command-status]').textContent=text;this.layoutComposer();}
 send(){if(this.composing||!this.draft.trim())return;this.append(this.draft);this.draft='';this.root.querySelector('textarea').value='';this.commandStatus(bilingual('Stored in this fixture conversation only.','仅加入当前模拟会话。'));}
 get dirty(){return true;}
 save(){return true;}
 discard(){this.draft='';this.messages=[];}
 snapshot(){return {state:this.state,draft:this.draft,messages:this.messages};}
 destroy(){this.resize?.disconnect();disposeControls(this.root);this.abort.abort();}
}
export {fixtures};
